- type: rank # CCM14
  id: RMCRankOperator
  name: Оператор
  prefix: опер.

- type: rank
  id: RMCRankOperative
  name: Оперативник
  prefix: Опер.

- type: rank
  id: RMCRankSynthetic
  name: Синтетик
  prefix: Синт.
  paygrade: E8

- type: rank
  id: RMCRankSyntheticMG
  name: Синтетик
  prefix: Синт.
  paygrade: E9

- type: rank
  id: RMCRankSyntheticColonist
  name: Синтетик
  prefix: Синт.
