using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._RMC14.Vendors;

[GenerateTypedNameReferences]
public sealed partial class CMAutomatedVendorEntry : Control
{
    private StyleNano.UiColorTheme _appliedTheme;

    public CMAutomatedVendorEntry()
    {
        RobustXamlLoader.Load(this);
        _appliedTheme = StyleNano.CurrentTheme;
        UpdateTheme();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_appliedTheme == StyleNano.CurrentTheme)
            return;

        _appliedTheme = StyleNano.CurrentTheme;
        UpdateTheme();
    }

    // CCM: vendor row chrome refresh.
    private void UpdateTheme()
    {
        var blue = StyleNano.CurrentTheme == StyleNano.UiColorTheme.Blue;
        var chrome = blue ? Color.FromHex("#3D6795") : Color.FromHex("#345A3F");
        var panel = blue ? Color.FromHex("#0F1827").WithAlpha(0.96f) : Color.FromHex("#141B14").WithAlpha(0.96f);
        var amountPanel = blue ? Color.FromHex("#13243A") : Color.FromHex("#172217");
        var helpText = blue ? Color.FromHex("#BFD6F0") : Color.FromHex("#C9DFC9");

        IconFrame.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = panel,
            BorderColor = chrome.WithAlpha(0.72f),
            BorderThickness = new Thickness(1),
        };

        AmountFrame.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = amountPanel,
            BorderColor = chrome.WithAlpha(0.72f),
            BorderThickness = new Thickness(1),
        };

        TooltipFrame.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = panel,
            BorderColor = chrome.WithAlpha(0.55f),
            BorderThickness = new Thickness(1),
        };

        TooltipLabel.FontColorOverride = helpText;
    }
}
