using Content.Client.Stylesheets;
using Content.Shared._RMC14.Vendors;
using Robust.Client.Graphics;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Vendors;

[GenerateTypedNameReferences]
public sealed partial class CMAutomatedVendorSection : Control
{
    public CMVendorSection? Section;

    public CMAutomatedVendorSection()
    {
        RobustXamlLoader.Load(this);
        UpdateTheme();
    }

    private void UpdateTheme()
    {
        SectionSeparator.Color = StyleNano.CurrentTheme == StyleNano.UiColorTheme.Blue
            ? Color.FromHex("#4972A1")
            : Color.FromHex("#2F6B46");
    }
}

// # CCM priority rework
