using Content.Client.Stylesheets;
using Content.Shared._RMC14.Vendors;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._RMC14.Vendors;

[GenerateTypedNameReferences]
public sealed partial class CMAutomatedVendorSection : Control
{
    private StyleNano.UiColorTheme _appliedTheme;

    public CMVendorSection? Section;

    public CMAutomatedVendorSection()
    {
        RobustXamlLoader.Load(this);
        _appliedTheme = StyleNano.CurrentTheme;
        UpdateTheme();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_appliedTheme == StyleNano.CurrentTheme)
            return;

        _appliedTheme = StyleNano.CurrentTheme;
        UpdateTheme();
    }

    // CCM: vendor section card refresh.
    private void UpdateTheme()
    {
        var blue = StyleNano.CurrentTheme == StyleNano.UiColorTheme.Blue;
        var chrome = blue ? Color.FromHex("#4972A1") : Color.FromHex("#2F6B46");
        var panel = blue ? Color.FromHex("#0F1B2C").WithAlpha(0.94f) : Color.FromHex("#101A12").WithAlpha(0.94f);

        SectionSeparator.Color = chrome;
        SectionPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = panel,
            BorderColor = chrome.WithAlpha(0.45f),
            BorderThickness = new Thickness(1),
        };
    }
}

// # CCM priority rework
