using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._RMC14.Vendors;

[GenerateTypedNameReferences]
public sealed partial class CMAutomatedVendorWindow : DefaultCMWindow
{
    private StyleNano.UiColorTheme _appliedTheme;

    public CMAutomatedVendorWindow()
    {
        RobustXamlLoader.Load(this);
        _appliedTheme = StyleNano.CurrentTheme;
        UpdateTheme();
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_appliedTheme == StyleNano.CurrentTheme)
            return;

        _appliedTheme = StyleNano.CurrentTheme;
        UpdateTheme();
    }

    // CCM: vendor window palette refresh.
    private void UpdateTheme()
    {
        var blue = StyleNano.CurrentTheme == StyleNano.UiColorTheme.Blue;
        var chrome = blue ? Color.FromHex("#4972A1") : Color.FromHex("#2F6B46");
        var softChrome = blue ? Color.FromHex("#2A4363") : Color.FromHex("#1C3425");
        var panel = blue ? Color.FromHex("#101D31").WithAlpha(0.98f) : Color.FromHex("#0D1710").WithAlpha(0.97f);
        var panelAlt = blue ? Color.FromHex("#14263F").WithAlpha(0.98f) : Color.FromHex("#112016").WithAlpha(0.97f);

        SearchPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = panel,
            BorderColor = chrome,
            BorderThickness = new Thickness(1),
        };

        ReagentsPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = panelAlt,
            BorderColor = softChrome,
            BorderThickness = new Thickness(1),
        };

        SectionsPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = panel,
            BorderColor = chrome,
            BorderThickness = new Thickness(1),
        };

        HeaderSeparator.Color = chrome;
        PointsLabel.FontColorOverride = blue ? Color.FromHex("#AFCBEE") : Color.FromHex("#B6D9C0");
    }
}

// # CCM priority rework
