using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Vendors;

[GenerateTypedNameReferences]
public sealed partial class CMAutomatedVendorWindow : DefaultCMWindow
{
    public CMAutomatedVendorWindow()
    {
        RobustXamlLoader.Load(this);
        UpdateTheme();
    }

    private void UpdateTheme()
    {
        HeaderSeparator.Color = StyleNano.CurrentTheme == StyleNano.UiColorTheme.Blue
            ? Color.FromHex("#4972A1")
            : Color.FromHex("#2F6B46");
    }
}

// # CCM priority rework

