using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client._RMC14.Vendors;

[GenerateTypedNameReferences]
public sealed partial class CMAutomatedVendorPanel : Control
{
    private static readonly Color DefaultColorGreen = Color.FromHex("#102117");
    private static readonly Color DefaultBorderColorGreen = Color.FromHex("#2F6B46");
    private static readonly Color DefaultHoveredColorGreen = Color.FromHex("#163125");
    private static readonly Color DefaultPressedColorGreen = Color.FromHex("#1D402F");
    private static readonly Color DisabledColorGreen = Color.FromHex("#15231C");

    private static readonly Color DefaultColorBlue = Color.FromHex("#14233B");
    private static readonly Color DefaultBorderColorBlue = Color.FromHex("#4972A1");
    private static readonly Color DefaultHoveredColorBlue = Color.FromHex("#1A3152");
    private static readonly Color DefaultPressedColorBlue = Color.FromHex("#224675");
    private static readonly Color DisabledColorBlue = Color.FromHex("#1A2433");

    private StyleNano.UiColorTheme _appliedTheme;
    private Color _pressedColor;
    private bool _useCustomPalette;

    public static Color DefaultColor =>
        StyleNano.CurrentTheme == StyleNano.UiColorTheme.Blue ? DefaultColorBlue : DefaultColorGreen;
    public static Color DefaultBorderColor =>
        StyleNano.CurrentTheme == StyleNano.UiColorTheme.Blue ? DefaultBorderColorBlue : DefaultBorderColorGreen;
    public static Color DefaultHoveredColor =>
        StyleNano.CurrentTheme == StyleNano.UiColorTheme.Blue ? DefaultHoveredColorBlue : DefaultHoveredColorGreen;

    public Color Color;
    public Color BorderColor;
    public Color HoveredColor;

    public CMAutomatedVendorPanel()
    {
        RobustXamlLoader.Load(this);
        _appliedTheme = StyleNano.CurrentTheme;

        Button.OnDrawModeChanged += UpdateColor;
        UseDefaultPalette();
        UpdateColor();
    }

    private void UpdateColor()
    {
        var panel = (StyleBoxFlat) Panel.PanelOverride!;
        var disabledColor = StyleNano.CurrentTheme == StyleNano.UiColorTheme.Blue
            ? DisabledColorBlue
            : DisabledColorGreen;

        panel.BackgroundColor = Button.Disabled
            ? disabledColor
            : Button.Pressed
                ? _pressedColor
                : Button.IsHovered
                    ? HoveredColor
                    : Color;

        panel.BorderColor = BorderColor;
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (_appliedTheme == StyleNano.CurrentTheme)
            return;

        _appliedTheme = StyleNano.CurrentTheme;
        if (!_useCustomPalette)
            ApplyTheme();

        UpdateColor();
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        UpdateColor();
    }

    // CCM: let special rows keep their own palette instead of being reset on hover.
    public void SetPalette(Color color, Color borderColor, Color hoveredColor, Color? pressedColor = null)
    {
        _useCustomPalette = true;
        Color = color;
        BorderColor = borderColor;
        HoveredColor = hoveredColor;
        _pressedColor = pressedColor ?? hoveredColor;
        UpdateColor();
    }

    public void UseDefaultPalette()
    {
        _useCustomPalette = false;
        ApplyTheme();
    }

    private void ApplyTheme()
    {
        if (StyleNano.CurrentTheme == StyleNano.UiColorTheme.Blue)
        {
            Color = DefaultColorBlue;
            BorderColor = DefaultBorderColorBlue;
            HoveredColor = DefaultHoveredColorBlue;
            _pressedColor = DefaultPressedColorBlue;
            return;
        }

        Color = DefaultColorGreen;
        BorderColor = DefaultBorderColorGreen;
        HoveredColor = DefaultHoveredColorGreen;
        _pressedColor = DefaultPressedColorGreen;
    }
}

// # CCM priority rework
