using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Vendors;

[GenerateTypedNameReferences]
public sealed partial class CMAutomatedVendorPanel : Control
{
    private static readonly Color DefaultColorGreen = Color.FromHex("#0F1A13");
    private static readonly Color DefaultBorderColorGreen = Color.FromHex("#2F6B46");
    private static readonly Color DefaultHoveredColorGreen = Color.FromHex("#3A8057");
    private static readonly Color DisabledColorGreen = Color.FromHex("#1A2B21");

    private static readonly Color DefaultColorBlue = Color.FromHex("#141F2F");
    private static readonly Color DefaultBorderColorBlue = Color.FromHex("#4972A1");
    private static readonly Color DefaultHoveredColorBlue = Color.FromHex("#5A88BF");
    private static readonly Color DisabledColorBlue = Color.FromHex("#1A2433");

    public static Color DefaultColor =>
        StyleNano.CurrentTheme == StyleNano.UiColorTheme.Blue ? DefaultColorBlue : DefaultColorGreen;
    public static Color DefaultBorderColor =>
        StyleNano.CurrentTheme == StyleNano.UiColorTheme.Blue ? DefaultBorderColorBlue : DefaultBorderColorGreen;
    public static Color DefaultHoveredColor =>
        StyleNano.CurrentTheme == StyleNano.UiColorTheme.Blue ? DefaultHoveredColorBlue : DefaultHoveredColorGreen;

    public Color Color;
    public Color BorderColor;
    public Color HoveredColor;

    public CMAutomatedVendorPanel()
    {
        RobustXamlLoader.Load(this);

        Button.OnDrawModeChanged += UpdateColor;
        UpdateColor();
    }

    private void UpdateColor()
    {
        ApplyTheme();
        var panel = (StyleBoxFlat) Panel.PanelOverride!;
        var disabledColor = StyleNano.CurrentTheme == StyleNano.UiColorTheme.Blue
            ? DisabledColorBlue
            : DisabledColorGreen;

        panel.BackgroundColor = Button.Disabled
            ? disabledColor
            : Button.IsHovered ? HoveredColor : Color;

        panel.BorderColor = BorderColor;
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        UpdateColor();
    }

    private void ApplyTheme()
    {
        if (StyleNano.CurrentTheme == StyleNano.UiColorTheme.Blue)
        {
            Color = DefaultColorBlue;
            BorderColor = DefaultBorderColorBlue;
            HoveredColor = DefaultHoveredColorBlue;
            return;
        }

        Color = DefaultColorGreen;
        BorderColor = DefaultBorderColorGreen;
        HoveredColor = DefaultHoveredColorGreen;
    }

}

// # CCM priority rework
