using Content.Shared._CCM.Mech;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._CCM.Mech.Ui.Equipment;

[GenerateTypedNameReferences]
public sealed partial class CCMMechSoundboardUiFragment : BoxContainer
{
    public event Action<int>? OnPlayAction;

    public CCMMechSoundboardUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void UpdateContents(MechSoundboardUiState state)
    {
        Sounds.Clear();
        Sounds.ClearSelected();
        foreach (var sound in state.Sounds)
        {
            Sounds.AddItem(Loc.GetString($"mech-soundboard-{sound}")).OnSelected += item => {
                OnPlayAction?.Invoke(Sounds.IndexOf(item));
            };
        }
    }
}
