using System;
using System.Collections.Generic;
using Robust.Client.Graphics;
using Content.Client.Resources;
using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Input;
using Robust.Shared.Maths;

namespace Content.Client.Options.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class EscapeMenu : DefaultCMWindow
    {
        public EscapeMenu()
        {
            RobustXamlLoader.Load(this);
            ApplyButtonTheme();
        }

        private void ApplyButtonTheme()
        {
            var cache = IoCManager.Resolve<IResourceCache>();
            var font = cache.GetFont("/Fonts/Bedstead/bedstead.otf", 15);

            foreach (var button in EnumerateMenuButtons())
            {
                button.Label.FontOverride = font;
                button.Label.Align = Label.AlignMode.Center;
                button.Label.Margin = new Thickness(0);

                ApplyMenuButtonStyle(button);

                button.OnMouseEntered += _ => ApplyMenuButtonStyle(button, hovered: true);
                button.OnMouseExited += _ => ApplyMenuButtonStyle(button);
                button.OnKeyBindDown += args =>
                {
                    if (args.Function != EngineKeyFunctions.UIClick)
                        return;

                    ApplyMenuButtonStyle(button, pressed: true);
                };
                button.OnKeyBindUp += args =>
                {
                    if (args.Function != EngineKeyFunctions.UIClick)
                        return;

                    ApplyMenuButtonStyle(button);
                };
            }
        }

        private IEnumerable<Button> EnumerateMenuButtons()
        {
            yield return VoteCallButton;
            yield return RulesButton;
            yield return GuidebookButton;
            yield return AchievementsButton;
            yield return SponsorshipButton;
            yield return WikiButton;
            yield return OptionsButton;
            yield return DisconnectButton;
            yield return QuitButton;
        }

        private static void ApplyMenuButtonStyle(Button button, bool hovered = false, bool pressed = false)
        {
            var baseColor = StyleNano.LobbyMenuButtonBase;
            var pressedColor = StyleNano.LobbyMenuButtonPressed;
            var hoverAccent = StyleNano.LobbyMenuButtonBase;

            if (button.Disabled)
            {
                button.StyleBoxOverride = new StyleBoxFlat
                {
                    BackgroundColor = StyleNano.LobbyMenuButtonDisabledCrt,
                    BorderColor = StyleNano.LobbyMenuButtonDisabledCrt,
                    BorderThickness = new Thickness(1),
                    ContentMarginLeftOverride = 8,
                    ContentMarginTopOverride = 6,
                    ContentMarginRightOverride = 8,
                    ContentMarginBottomOverride = 6,
                };
                button.Label.FontColorOverride = Color.Black;
                return;
            }

            button.StyleBoxOverride = new StyleBoxFlat
            {
                BackgroundColor = pressed
                    ? pressedColor
                    : hovered
                        ? Color.Transparent
                        : baseColor,
                BorderColor = pressed
                    ? pressedColor
                    : hovered
                        ? hoverAccent
                        : baseColor,
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 8,
                ContentMarginTopOverride = 6,
                ContentMarginRightOverride = 8,
                ContentMarginBottomOverride = 6,
            };

            button.Label.FontColorOverride = pressed
                ? Color.Black
                : hovered
                    ? hoverAccent
                    : Color.Black;
        }
    }
}

