using Content.Client.Administration.Managers;
using Content.Client.Options.UI.Tabs;
using Content.Client._RMC14.UserInterface.Options;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Options.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class OptionsMenu : DefaultCMWindow
    {
        [Dependency] private readonly IClientAdminManager _adminManager = default!;
        private readonly MiscTab _miscTab;
        private readonly GraphicsTab _graphicsTab;
        private readonly KeyRebindTab _keyRebindTab;
        private readonly AudioTab _audioTab;
        private readonly VoicelinesTab _voicelinesTab;
        private readonly AccessibilityTab _accessibilityTab;
        private readonly AdminOptionsTab _adminOptionsTab;
        private bool _adminTabAdded;

        public OptionsMenu()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            _miscTab = new MiscTab();
            _graphicsTab = new GraphicsTab();
            _keyRebindTab = new KeyRebindTab();
            _audioTab = new AudioTab();
            _voicelinesTab = new VoicelinesTab();
            _accessibilityTab = new AccessibilityTab();
            _adminOptionsTab = new AdminOptionsTab();

            Tabs.AddTab(_miscTab, Loc.GetString("ui-options-tab-misc"));
            Tabs.AddTab(_graphicsTab, Loc.GetString("ui-options-tab-graphics"));
            Tabs.AddTab(_keyRebindTab, Loc.GetString("ui-options-tab-controls"));
            Tabs.AddTab(_audioTab, Loc.GetString("ui-options-tab-audio"));
            Tabs.AddTab(_voicelinesTab, Loc.GetString("rmc-ui-options-tab-voicelines")); // RMC14
            Tabs.AddTab(_accessibilityTab, Loc.GetString("ui-options-tab-accessibility"));

            OnClose += () => _keyRebindTab.RefreshKeyControls();

            UpdateTabs();
        }

        public void UpdateTabs()
        {
            var isAdmin = _adminManager.IsAdmin(true);
            if (isAdmin)
            {
                if (!_adminTabAdded)
                {
                    Tabs.AddTab(_adminOptionsTab, Loc.GetString("ui-options-tab-admin"));
                    _adminTabAdded = true;
                }
            }
            else if (_adminTabAdded)
            {
                Tabs.RemoveTab(_adminOptionsTab);
                _adminTabAdded = false;
            }

            _graphicsTab.Control.ReloadValues();
            _miscTab.Control.ReloadValues();
            _accessibilityTab.Control.ReloadValues();
            _audioTab.Control.ReloadValues();
            _voicelinesTab.Control.ReloadValues();
            _keyRebindTab.RefreshKeyControls();
            if (_adminTabAdded)
                _adminOptionsTab.Control.ReloadValues();
        }

    public void SelectTabIndex(int tab)
    {
        Tabs.CurrentTab = tab;
    }
}
// # CCM priority rework
}

