using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Xenonids.Evolution;

[GenerateTypedNameReferences]
public sealed partial class XenoEvolutionWindow : DefaultCMWindow
{
    public XenoEvolutionWindow()
    {
        RobustXamlLoader.Load(this);
    }
}

