using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._RMC14.Xenonids.Evolution
{
    [GenerateTypedNameReferences]
    public sealed partial class XenoStrainConfirmWindow : DefaultCMWindow
    {
        private StyleNano.UiColorTheme _appliedTheme;

        public event System.Action? OnConfirm;

        public XenoStrainConfirmWindow()
        {
            RobustXamlLoader.Load(this);
            MinSize = new(320f, 420f);
            SetSize = new(340f, 450f);
            ApplyThemeColors(force: true);

            ConfirmButton.OnPressed += _ => OnConfirm?.Invoke();
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);
            ApplyThemeColors();
        }

        public void SetInfo(string name, Texture? sprite, string? description)
        {
            NameLabel.Text = name;
            Sprite.Texture = sprite;

            if (description != null)
            {
                DescriptionLabel.SetMessage(
                    FormattedMessage.FromMarkupPermissive(Loc.GetString(description))
                );
            }
        }

        private void ApplyThemeColors(bool force = false)
        {
            var theme = StyleNano.CurrentTheme;
            if (!force && theme == _appliedTheme)
                return;

            _appliedTheme = theme;

            var blue = theme == StyleNano.UiColorTheme.Blue;
            var title = blue ? Color.FromHex("#EAF3FF") : Color.FromHex("#F2FFF4");
            var accent = blue ? Color.FromHex("#4E84DC") : Color.FromHex("#3FD35B");
            var border = blue ? Color.FromHex("#2A67B8") : Color.FromHex("#2B7E45");
            var header = blue ? Color.FromHex("#13345F") : Color.FromHex("#0A2C18");
            var body = blue ? Color.FromHex("#0E2950").WithAlpha(0.96f) : Color.FromHex("#082512").WithAlpha(0.96f);

            HeaderPanel.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = header,
                BorderColor = border,
                BorderThickness = new Thickness(1),
            };

            BodyPanel.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = body,
                BorderColor = border.WithAlpha(0.90f),
                BorderThickness = new Thickness(1),
            };

            WindowTitleLabel.FontColorOverride = title;
            NameLabel.FontColorOverride = accent;
            ConfirmButton.StyleBoxOverride = new StyleBoxFlat
            {
                BackgroundColor = blue ? Color.FromHex("#133B74") : Color.FromHex("#0A4D11"),
                BorderColor = border,
                BorderThickness = new Thickness(1),
                ContentMarginLeftOverride = 10,
                ContentMarginTopOverride = 4,
                ContentMarginRightOverride = 10,
                ContentMarginBottomOverride = 4,
            };
            ConfirmButton.Label.FontColorOverride = title;
        }
    }
}
