- type: rank
  id: RMCRankWeYaTrainee
  name: Стажёр
  prefix: Стаж.
  paygrade: WYC1

- type: rank
  id: RMCRankWeYaJuniorExecutive
  name: Младший чиновник
  prefix: Мл. Чин.
  paygrade: WYC2

- type: rank
  id: RMCRankWeYaExecutive
  name: Чиновник
  prefix: Чин.
  paygrade: WYC3

- type: rank
  id: RMCRankWeYaSeniorExecutive
  name: Старший Чиновник
  prefix: Ст. Чин.
  paygrade: WYC4

- type: rank
  id: RMCRankWeYaExecutiveSpecialist
  name: Административнй специалист
  prefix: Адм. Спец.
  paygrade: WYC5

- type: rank
  id: RMCRankWeYaExecutiveSupervisor
  name: Административный Супервайзер
  prefix: Адм. Суп.
  paygrade: WYC6

- type: rank
  id: RMCRankWeYaAssistantManager
  name: Помощник Менеджера
  prefix: Пом. Мен.
  paygrade: WYC7

- type: rank
  id: RMCRankWeYaDivisionManager
  name: Менеджер Крыла
  prefix: Мен. Кр.
  paygrade: WYC8

- type: rank
  id: RMCRankWeYaChiefExecutive
  name: Старший Администратор
  prefix: Ст. Адм.
  paygrade: WYC9

- type: rank
  id: RMCRankWeYaDeputyDirector
  name: Заместитель Директора
  prefix: Зам. Дир.
  paygrade: WYC10

- type: rank
  id: RMCRankWeYaDirector
  name: Директор
  prefix: Директор
  paygrade: WYC11

# Lawyers
- type: rank
  id: RMCRankWeYaLegalSpecialist
  name: Правовой Специалист
  prefix: Прав. Спец.
  paygrade: WYC5

- type: rank
  id: RMCRankWeYaLegalSupervisor
  name: Юридический Руководитель
  prefix: Юр. Рук.
  paygrade: WYC6

# Pilots
- type: rank
  id: RMCRankWeYaPilotOfficer
  name: Капитан
  prefix: Кап.
  paygrade: WYPO2

# Synthetics
# A/N: probably not particularly useful, but I want some variety 
- type: rank
  id: RMCRankWeYaUtilitySynth # Simple labor synths (drivers, cargo haulers, repairmen)
  name: Сервисный Синтетик
  prefix: Серв. Синт.
  paygrade: WYS1
  
- type: rank
  id: RMCRankWeYaAssistantSynth # Secretaries, data entry, analysis, PR, etc.
  name: Синтетик-Адъютант
  prefix: СинтАд.
  paygrade: WYS2
  
- type: rank
  id: RMCRankWeYaAdministrativeSynth # Project managers, directors, overseers (with organic oversight obv)
  name: Административный Синтетик
  prefix: Адм. Синт.
  paygrade: WYS3