- type: rank
  id: RMCRankWeYaOperator
  name: Ефрейтор
  prefix: Ефр.
  paygrade: PMC-OP

- type: rank
  id: RMCRankWeYaEnforcer
  name: Силовик
  prefix: Сил.
  paygrade: PMC-EN

- type: rank
  id: RMCRankWeYaVehicleSpecialist
  name: Специалист-механик
  prefix: Спц-мех.
  paygrade: PMC-VS

- type: rank
  id: RMCRankWeYaSupportSpecialist
  name: Боевая Поддержка
  prefix: БП.
  paygrade: PMC-SS

- type: rank
  id: RMCRankWeYaMedicalSpecialist
  name: Медик
  prefix: Мед.
  paygrade: PMC-MS

- type: rank
  id: RMCRankWeYaWeaponSpecialist
  name: Ветеран
  prefix: Вет.
  paygrade: PMC-WS

- type: rank
  id: RMCRankWeYaXenoSpecialist
  name: Спец по сдерживанию
  prefix: СпС.
  paygrade: PMC-XS

- type: rank
  id: RMCRankWeYaTraumaSurgeon
  name: Хирург
  prefix: Др.
  paygrade: PMC-DOC

- type: rank
  id: RMCRankWeYaCorporateTechnician
  name: Техник
  prefix: Тех.
  paygrade: PMC-TEC

- type: rank
  id: RMCRankWeYaEliteResponder
  name: Коммандо
  prefix: Коман.
  paygrade: PMC-ELR

- type: rank
  id: RMCRankWeYaEliteMedic
  name: Санитар Коммандо
  prefix: СК.
  paygrade: PMC-ELM

- type: rank
  id: RMCRankWeYaEliteGunner
  name: Пулемётчик Коммандо
  prefix: ПК.
  paygrade: PMC-ELG

- type: rank
  id: RMCRankWeYaPMCSynthetic
  name: Синтетик
  prefix: СИНТ.
  paygrade: PMC-SYN

- type: rank
  id: RMCRankWeYaTeamLeader
  name: Старшина
  prefix: Стр.
  paygrade: PMC-TL

- type: rank
  id: RMCRankWeYaFieldOperaionsLeader
  name: Урядник
  prefix: Уряд.
  paygrade: PMC-FOL

- type: rank
  id: RMCRankWeYaForceLeader
  name: Поручник
  prefix: Пор.
  paygrade: PMC-FL

- type: rank
  id: RMCRankWeYaEliteTeamLeader
  name: Аш-Маршал
  prefix: АМ.
  paygrade: PMC-ETL

- type: rank
  id: RMCRankWeYaSiteDirector
  name: Куратор Подразделения ЧВК
  prefix: Кур.
  paygrade: PMC-DIR

- type: rank
  id: RMCRankWeYaForceCommand
  name: Ротмеистер
  prefix: РМ.
  paygrade: PMC-FCO

- type: rank
  id: RMCRankWeYaWhiteout
  name: Отряд "Белая мгла"
  prefix: ОБМ.
  paygrade: ???