- type: rank
  id: RMCRankCMBDeputy
  name: Помощник Маршала
  prefix: Пом. Мар.
  paygrade: CMBD

- type: rank
  id: RMCRankCMBMarshal
  name: Колониальный Маршал
  prefix: Марш
  paygrade: CMBM

- type: rank
  id: RMCRankCMBInvestigativeSynthetic
  name: Синтетик БКМ
  prefix: Syn.

- type: rank
  id: RMCRankCMBRiotControlSynthetic
  name: Синтетик Карательного Отряда
  prefix: Синт.

- type: rank
  id: RMCRankCMBRiotControlOfficer
  name: Лидер
  prefix: Лид.

- type: rank
  id: RMCRankCMBMedicalTechnician
  name: Полевой Медик
  prefix: Мед.

- type: rank
  id: RMCRankCMBBreachingTechnician
  name: Штурмовик
  prefix: Штурм.

- type: rank
  id: RMCRankCMBSWATSpecialist
  name: Специалист
  prefix: Спец.

- type: rank
  id: RMCRankICBAgent
  name: Представитель Антимонопольного Бюро
  prefix: Агент

- type: rank
  id: RMCRankICBCorporateLiaison
  name: Связной Антимонопольного Бюро
  prefix: Связ.
  paygrade: ICBL

- type: rank
  id: RMCRankIHROObserver
  name: Уполномоченный Наблюдатель по Правам Разумных Существ
  prefix: "Набл."
  paygrade: ILRO
