# TSEPA - (Three Suns Empire Policing Authority) - TSE style Police, like the CMB but for heavy TSE focused colonies. Please change when we have a new name for the sector.

- type: rank
  id: RMCRankTSEPAConstable
  name: Офицер
  prefix: Оф.

- type: rank
  id: RMCRankTSEPASeniorConstable
  name: Старший Офицер
  prefix: Ст. Оф.

- type: rank
  id: RMCRankTSEPASergeant
  name: Сержант
  prefix: Серж.

- type: rank
  id: RMCRankTSEPAInspector
  name: Инспектор
  prefix: Инсп.

- type: rank
  id: RMCRankTSEPAChiefInspector
  name: Старший Инспектор
  prefix: Ст. Инсп.

- type: rank
  id: RMCRankTSEPACommander
  name: Командир
  prefix: Кмдр.

- type: rank
  id: RMCRankTSEPADeputyCommissioner
  name: Помощник Комиссионера
  prefix: Пом. Ком.

- type: rank
  id: RMCRankTSEPACommissioner
  name: Комиссионер
  prefix: Ком.

