using System.Numerics;
using Content.Client.UserInterface;
using Content.Shared._RMC14.Xenonids.Projectile.Parasite;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Localization;

namespace Content.Client._RMC14.Xenonids.Projectile.Parasite;

[GenerateTypedNameReferences]
public sealed partial class ReserveParasitesWindow : DefaultWindow
{
    [Dependency] private readonly ILocalizationManager _localization = default!;

    private int _maxRegular;
    private bool _isUpdating;

    public ReserveParasitesWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    private SpinBox _reserveBar = default!;
    private Button _applyButton = default!;

    public SpinBox ReserveBar => _reserveBar;
    public Button ApplyButton => _applyButton;

    public void SetReserveShown(int currentRegular, int maxRegular)
    {
        Title = Loc.GetString("rmc-xeno-reserve-parasites-title");

        _maxRegular = maxRegular;

        var vBox = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(4),
            Children =
            {
                new BoxContainer
                {
                    Orientation = BoxContainer.LayoutOrientation.Horizontal,
                    Children =
                    {
                        new Label
                        {
                            Text = Loc.GetString("rmc-xeno-reserve-parasites-label"),
                            MinSize = new Vector2(130, 0)
                        },
                        (_reserveBar = new SpinBox
                        {
                            Value = currentRegular,
                            HorizontalExpand = true
                        })
                    }
                },
                new Label
                {
                    Text = Loc.GetString("rmc-xeno-reserve-royal-parasites-unavailable"),
                    Modulate = Color.FromHex("#FFC0C0"),
                    Margin = new Thickness(4, 4, 4, 4)
                },
                (_applyButton = new Button
                {
                    Text = Loc.GetString("rmc-xeno-reserve-parasites-apply"),
                    HorizontalAlignment = HAlignment.Center
                })
            }
        };

        Contents.AddChild(vBox);
        MinSize = new Vector2(300, 0);

        _isUpdating = true;
        _isUpdating = false;

        _reserveBar.ValueChanged += args =>
        {
            if (_isUpdating)
                return;

            _isUpdating = true;
            var value = Math.Clamp(args.Value, 0, _maxRegular);
            _reserveBar.Value = value;
            _isUpdating = false;
        };
    }
}
