using System.Linq;
using System.Numerics;
using System.Text.RegularExpressions;
using Content.Client.Stylesheets;
using Content.Shared._Forge.Sponsor;
using Content.Shared._Forge.TTS;
using Content.Shared.Humanoid;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;

namespace Content.Client._Forge.TTS;

[GenerateTypedNameReferences]
public sealed partial class TTSTab : Control
{
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;
    [Dependency] private readonly IPlayerManager _playerManager = default!;
    [Dependency] private readonly ISharedSponsorManager _sponsorMng = default!;
    [Dependency] private readonly IResourceCache _resCache = default!;

    // Bright colour used to mark the currently selected voice (CM's theme makes the
    // Caution button style indistinguishable from the default one).
    private static readonly Color SelectedColor = Color.FromHex("#FFD700");

    public event Action<string>? OnVoiceSelected;
    public event Action<string>? OnPreviewRequested;

    private List<TTSVoicePrototype> _allVoices = new();
    private List<TTSVoicePrototype> _filteredVoices = new();
    private Dictionary<string, List<TTSVoicePrototype>> _categorizedVoices = new();
    private string? _selectedVoiceId;

    private static readonly Regex CategoryRegex = new Regex(@"^(.*?)\s*\(([^)]+)\)\s*$", RegexOptions.Compiled);

    public TTSTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        LoadVoices();
        SearchEdit.OnTextChanged += OnSearchChanged;
    }

    private void LoadVoices()
    {
        foreach (var voice in _allVoices)
        {
            var name = Loc.GetString(voice.Name);
            var category = Loc.GetString("humanoid-profile-editor-voice-other");

            var match = CategoryRegex.Match(name);
            if (match.Success)
            {
                category = match.Groups[2].Value.Trim();
            }

            if (!_categorizedVoices.ContainsKey(category))
                _categorizedVoices[category] = new List<TTSVoicePrototype>();

            _categorizedVoices[category].Add(voice);
        }

        CategoriesContainer.RemoveAllChildren();

        foreach (var category in _categorizedVoices.Keys.OrderBy(k => k))
        {
            var button = new Button
            {
                Text = category,
                ToolTip = Loc.GetString("humanoid-profile-editor-voice-category-tooltip", ("category", category)),
                HorizontalExpand = true,
            };

            button.OnPressed += _ =>
            {
                SearchEdit.Text = category;
                UpdateResults();
            };

            CategoriesContainer.AddChild(button);
        }

        UpdateResults();
    }

    private void OnSearchChanged(LineEdit.LineEditEventArgs args)
    {
        UpdateResults();
    }

    private void UpdateResults()
    {
        VoicesGrid.RemoveAllChildren();
        _filteredVoices.Clear();

        var searchText = SearchEdit.Text.ToLowerInvariant();

        foreach (var voice in _allVoices)
        {
            var name = Loc.GetString(voice.Name).ToLowerInvariant();

            if (string.IsNullOrEmpty(searchText) ||
                name.Contains(searchText) ||
                voice.ID.ToLowerInvariant().Contains(searchText))
            {
                _filteredVoices.Add(voice);
            }
        }

        foreach (var voice in _filteredVoices)
        {
            var displayName = Loc.GetString(voice.Name);
            var canSelectVoice = CanUseVoice(voice);

            var voiceContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
                VerticalAlignment = VAlignment.Center
            };

            var isSelected = voice.ID == _selectedVoiceId;

            var selectButton = new Button
            {
                Text = isSelected ? $"» {displayName}" : displayName,
                ToolTip = canSelectVoice ? voice.ID : Loc.GetString("humanoid-profile-editor-voice-tooltip-sponsoronly"),
                HorizontalExpand = true,
                Disabled = !canSelectVoice,
                StyleClasses = { StyleBase.ButtonOpenRight }
            };

            if (isSelected)
            {
                selectButton.AddStyleClass(StyleBase.ButtonCaution);
                // Gold text reliably marks the selection regardless of the button stylebox.
                selectButton.Label.FontColorOverride = SelectedColor;
            }

            selectButton.OnPressed += _ =>
            {
                if (canSelectVoice)
                {
                    OnVoiceSelected?.Invoke(voice.ID);
                }
            };

            // Use a play texture instead of a glyph: the default UI font does not render U+25B6.
            var previewButton = new Button
            {
                MinSize = new Vector2(34, 0),
                ToolTip = Loc.GetString("humanoid-profile-editor-voice-tooltip-play"),
                StyleClasses = { StyleBase.ButtonOpenLeft }
            };

            previewButton.AddChild(new TextureRect
            {
                Texture = _resCache.GetResource<TextureResource>("/Textures/Interface/AdminActions/play.png").Texture,
                Stretch = TextureRect.StretchMode.KeepAspectCentered,
                MinSize = new Vector2(18, 18),
                VerticalAlignment = VAlignment.Center,
                HorizontalAlignment = HAlignment.Center,
                MouseFilter = MouseFilterMode.Ignore,
            });

            previewButton.OnPressed += _ =>
            {
                OnPreviewRequested?.Invoke(voice.ID);
            };

            voiceContainer.AddChild(selectButton);
            voiceContainer.AddChild(previewButton);

            VoicesGrid.AddChild(voiceContainer);
        }

        ResultsLabel.Text = Loc.GetString("humanoid-profile-editor-voice-match",
            ("filtered", _filteredVoices.Count), ("all", _allVoices.Count));
    }

    private bool CanUseVoice(TTSVoicePrototype voice)
    {
        if (voice.SponsorLevel == SponsorLevel.None)
            return true;

        var user = _playerManager.LocalUser;
        if (user != null && _sponsorMng.TryGetSponsor(user.Value, out var level))
            return level >= voice.SponsorLevel;

        return false;
    }

    public void UpdateControls(HumanoidCharacterProfile? profile, Sex sex)
    {
        if (profile == null)
            return;

        _selectedVoiceId = profile.Voice;

        _allVoices = _prototypeManager
            .EnumeratePrototypes<TTSVoicePrototype>()
            .Where(o => o.RoundStart && HumanoidCharacterProfile.CanHaveVoice(o, sex))
            .OrderBy(o => Loc.GetString(o.Name))
            .ToList();

        _categorizedVoices.Clear();
        LoadVoices();
    }

    public void SetSelectedVoice(string voiceId)
    {
        _selectedVoiceId = voiceId;
        UpdateResults();
    }
}
