- type: rank
  id: RMCRankFLFreelancer
  name: Наёмник
  prefix: Найм.

- type: rank
  id: RMCRankFLMedic
  name: Медик
  prefix: Мед.

- type: rank
  id: RMCRankFLLeader
  name: Лидер
  prefix: Шеф

- type: rank
  id: RMCRankFLEliteFreelancer
  name: Головорез
  prefix: ГР.

- type: rank
  id: RMCRankFLEliteHeavy
  name: Броненосец
  prefix: БН.

- type: rank
  id: RMCRankFLEliteEngineer
  name: Инженер
  prefix: Инж.

- type: rank
  id: RMCRankFLEliteMedic
  name: Санитар
  prefix: Сан.

- type: rank
  id: RMCRankFLEliteLeader
  name: Командор
  prefix: Босс
