- type: job
  parent: CCMJobProtomorphBase
  id: CCMProtomorphVenator
  name: ccm-job-name-protomorph-venator
  playTimeTracker: CCMJobProtomorphVenator

- type: playTimeTracker
  id: CCMJobProtomorphVenator
  isXeno: true
