# Colony

- type: rank
  id: RMCRankSPPMlts
  name: Милицонер
  prefix: Мил.
  paygrade: MLTS

- type: rank
  id: RMCRankSPPSMlts
  name: Старший Милиционер
  prefix: Ст. Мил.
  paygrade: SMLTS

- type: rank
  id: RMCRankSPPStrsh
  name: Старшина
  prefix: Старш.
  paygrade: STRSH

# Military

- type: rank
  id: RMCRankSPPRyadovoy
  name: Красноармеец
  prefix: КРАС.
  paygrade: E1

- type: rank
  id: RMCRankSPPEfreitor
  name: Ефрейтор
  prefix: Ефр.
  paygrade: E2

- type: rank
  id: RMCRankSPPMladshiySerzhant
  name: Младший Сержант
  prefix: Мл. Сжт.
  paygrade: E3

- type: rank
  id: RMCRankSPPSerzhant
  name: Сержант
  prefix: Сжт.
  paygrade: E4

- type: rank
  id: RMCRankSPPStarshiySerzhant
  name: Старший Сержант
  prefix: Ст. Сжт.
  paygrade: E5

- type: rank
  id: RMCRankSPPStarshyna
  name: Старшина
  prefix: StS.
  paygrade: E6

# THE RANKS BELOW ARE USED FOR THE SPP DEATHSQUAD, PLEASE DON'T USE THEM FOR ANYTHING ELSE

- type: rank
  id: RMCRankSPPJuniorKommando
  name: Коммандос
  prefix: Комм.
  paygrade: E7

- type: rank
  id: RMCRankSPP2ndKommando
  name: Диверсант
  prefix: Див.
  paygrade: E8

- type: rank
  id: RMCRankSPP1stKommando
  name: Комиссар
  prefix: Ком.
  paygrade: E9

# THE RANKS ABOVE ARE USED FOR THE SPP DEATHSQUAD, PLEASE DON'T USE THEM FOR ANYTHING ELSE

- type: rank
  id: RMCRankSPPMladshiyLeytenant
  name: Младший Лейтенант
  prefix: Мл. Лейт.
  paygrade: O1

- type: rank
  id: RMCRankSPPStarshiyLeytenant
  name: Лейтенант
  prefix: Лейт.
  paygrade: O2

- type: rank
  id: RMCRankSPPKapitan
  name: Старший Лейтенант
  prefix: Ст. Тейт.
  paygrade: O3

- type: rank
  id: RMCRankSPPMayjor
  name: Капитан
  prefix: Кап.
  paygrade: O4

- type: rank
  id: RMCRankSPPPoliticalCommissar
  name: Народный Секретарь
  prefix: Нар. Сек.
  # This is a civilian rank, so it doesn't have a paygrade

- type: rank
  id: RMCRankSPPPodpolkovnik
  name: Майор
  prefix: Май.
  paygrade: O5

- type: rank
  id: RMCRankSPPPolkovnik
  name: Подполковник
  prefix: ПодП.
  paygrade: O6

- type: rank
  id: RMCRankSPPGeneralMayjor
  name: Полковник
  prefix: Полк.
  paygrade: O7

- type: rank
  id: RMCRankSPPGeneralLeytenant
  name: Генерал-Полковник
  prefix: ГенП.
  paygrade: O8

- type: rank
  id: RMCRankSPPGeneralPolkovnik
  name: Генерал-Майор
  prefix: ГенМ.
  paygrade: O9

- type: rank
  id: RMCRankSPPGeneralArmii
  name: Генерал-Капитан
  prefix: ГенК.
  paygrade: O10
