using Content.Shared.Humanoid;
using Content.Shared.Humanoid.Prototypes;
using Content.Shared.Preferences;
using Content.Client.Resources;
using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Maths;
using System.Numerics;
using Robust.Shared.Map;
using System;
using System.Collections.Generic;
using Content.Client.Humanoid;

namespace Content.Client.Lobby.UI
{
    /// <summary>
    /// Holds the entire character setup GUI, from character picks to individual character editing.
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class CharacterSetupGui : Control
    {
        [Dependency] private readonly IClientPreferencesManager _preferencesManager = default!;
        [Dependency] private readonly IEntityManager _entManager = default!;
        [Dependency] private readonly IPrototypeManager _protomanager = default!;
        [Dependency] private readonly IResourceCache _resourceCache = default!;

        private readonly HumanoidProfileEditor _profileEditor;
        private readonly List<(int Slot, ICharacterProfile Profile)> _carouselProfiles = new();
        private int _carouselIndex;
        private EntityUid _leftPreviewEntity;
        private EntityUid _centerPreviewEntity;
        private EntityUid _rightPreviewEntity;
        private EntityUid _leftFarPreviewEntity;
        private EntityUid _rightFarPreviewEntity;
        private string _centerPreviewSpeciesId = SharedHumanoidAppearanceSystem.DefaultSpecies;
        private bool _showClothes = true;
        private bool _deleteCounting;
        private bool _deleteReady;
        private float _deleteCountdown;
        private bool _dragging;
        private Vector2 _dragOffset;
        private Vector2 _manualPosition;
        private bool _hasManualPosition;
        private readonly Dictionary<SpriteView, float> _hoverRotationTimes = new();
        private readonly HashSet<SpriteView> _hoveredViews = new();
        private StyleNano.UiColorTheme _appliedTheme;
        private float _lastCarouselWidth = -1f;
        private CarouselLayoutMode _carouselLayoutMode = CarouselLayoutMode.Five;
        private enum CarouselLayoutMode
        {
            One,
            Three,
            Five
        }

        public event Action<int>? SelectCharacter;
        public event Action<int>? DeleteCharacter;
        public TextureButton CloseButtonControl => CloseButton;
        public bool HasManualPosition => _hasManualPosition;
        public Vector2 ManualPosition => _manualPosition;

        public CharacterSetupGui(HumanoidProfileEditor profileEditor)
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            _profileEditor = profileEditor;

            ApplyThemeColors(force: true);
            CharEditor.AddChild(profileEditor);
            LayoutContainer.SetAnchorPreset(CarouselLayout, LayoutContainer.LayoutPreset.Wide);
            LayoutContainer.SetAnchorPreset(CarouselBackgroundPanel, LayoutContainer.LayoutPreset.Wide);
            LayoutContainer.SetAnchorPreset(CarouselBorderPanel, LayoutContainer.LayoutPreset.Wide);
            LayoutContainer.SetAnchorPreset(CarouselSideShade, LayoutContainer.LayoutPreset.Wide);

            NewCharacterButton.OnPressed += _ => CreateCharacter();
            SaveCharacterButton.OnPressed += _ => _profileEditor.RequestSave();
            ResetCharacterButton.OnPressed += _ => _profileEditor.RequestReset();
            DeleteCharacterButton.OnPressed += _ => HandleDeletePressed();

            LeftFarNameLabel.AddStyleClass("CharacterCarouselName");
            LeftNameLabel.AddStyleClass("CharacterCarouselName");
            CenterNameLabel.AddStyleClass("CharacterCarouselName");
            CenterNameLabel.AddStyleClass("CharacterCarouselNameSelected");
            RightNameLabel.AddStyleClass("CharacterCarouselName");
            RightFarNameLabel.AddStyleClass("CharacterCarouselName");

            // CCM rework lobby - start
            MouseFilter = MouseFilterMode.Stop;
            LeftFarPreviewContainer.MouseFilter = MouseFilterMode.Stop;
            LeftPreviewContainer.MouseFilter = MouseFilterMode.Stop;
            CenterPreviewContainer.MouseFilter = MouseFilterMode.Stop;
            RightPreviewContainer.MouseFilter = MouseFilterMode.Stop;
            RightFarPreviewContainer.MouseFilter = MouseFilterMode.Stop;
            LeftFarPreviewContainer.OnKeyBindDown += args => PreviewClicked(args, -2);
            LeftPreviewContainer.OnKeyBindDown += args => PreviewClicked(args, -1);
            RightPreviewContainer.OnKeyBindDown += args => PreviewClicked(args, 1);
            RightFarPreviewContainer.OnKeyBindDown += args => PreviewClicked(args, 2);
            OnKeyBindDown += StartDrag;
            OnKeyBindUp += StopDrag;
            HookPreviewRotation(LeftFarPreviewContainer, LeftFarPreview);
            HookPreviewRotation(LeftPreviewContainer, LeftPreview);
            HookPreviewRotation(CenterPreviewContainer, CenterPreview, true);
            HookPreviewRotation(RightPreviewContainer, RightPreview);
            HookPreviewRotation(RightFarPreviewContainer, RightFarPreview);
            _profileEditor.ProfileChanged += _ => RefreshCenterPreviewFromEditor();
            _profileEditor.ShowClothesChanged += UpdateShowClothes;
            // CCM rework lobby - end
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);
            ApplyThemeColors();
            UpdateCarouselLayoutIfNeeded();
            UpdateRotation(args.DeltaSeconds);
            UpdateDeleteCountdown(args.DeltaSeconds);
        }

        // CCM rework lobby - start
        private void ApplyThemeColors(bool force = false)
        {
            var theme = StyleNano.CurrentTheme;
            if (!force && theme == _appliedTheme)
                return;

            _appliedTheme = theme;

            var panelTex = _resourceCache.GetTexture("/Textures/Interface/Nano/button.svg.96dpi.png");
            var frameColor = theme == StyleNano.UiColorTheme.Blue
                ? Color.FromHex("#0B3578")
                : Color.FromHex("#16301F");
            var carouselBackgroundColor = theme == StyleNano.UiColorTheme.Blue
                ? Color.FromHex("#06152A").WithAlpha(0.94f)
                : Color.FromHex("#06150C").WithAlpha(0.94f);
            var carouselSideShadeColor = Color.Transparent;
            var dividerColor = theme == StyleNano.UiColorTheme.Blue
                ? Color.FromHex("#165197").WithAlpha(0.95f)
                : Color.FromHex("#2B7E45").WithAlpha(0.95f);

            var back = new StyleBoxTexture
            {
                Texture = panelTex,
                Modulate = frameColor
            };
            back.SetPatchMargin(StyleBox.Margin.All, 10);
            BackgroundPanel.PanelOverride = back;
            MenuBorderPanel.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.Transparent,
                BorderColor = dividerColor,
                BorderThickness = new Thickness(1)
            };
            CarouselBackgroundPanel.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = carouselBackgroundColor
            };
            CarouselBorderPanel.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = Color.Transparent,
                BorderColor = dividerColor,
                BorderThickness = new Thickness(1)
            };
            CarouselLeftShade.PanelOverride = new StyleBoxFlat { BackgroundColor = carouselSideShadeColor };
            CarouselRightShade.PanelOverride = new StyleBoxFlat { BackgroundColor = carouselSideShadeColor };

            EditorTopDivider.PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = dividerColor,
                ContentMarginTopOverride = 2
            };
        }
        // CCM rework lobby - end

        /// <summary>
        /// Disposes and reloads all character picker buttons from the preferences data.
        /// </summary>
        public void ReloadCharacterPickers()
        {
            // CCM rework lobby - start
            ResetDeleteState();
            _carouselProfiles.Clear();
            if (!_preferencesManager.ServerDataLoaded)
                return;

            var selectedSlot = _preferencesManager.Preferences?.SelectedCharacterIndex;
            var allowedSpecies = new HashSet<string> { "Human", "Avali", "Arachnid", "Moth", "Felinid", "Dwarf" };
            foreach (var (slot, character) in _preferencesManager.Preferences!.Characters)
            {
                if (character is HumanoidCharacterProfile humanoidProfile &&
                    !allowedSpecies.Contains(humanoidProfile.Species.Id))
                {
                    continue;
                }

                _carouselProfiles.Add((slot, character));
            }

            _carouselIndex = 0;
            if (selectedSlot != null)
            {
                var selectedIndex = _carouselProfiles.FindIndex(p => p.Slot == selectedSlot.Value);
                if (selectedIndex >= 0)
                    _carouselIndex = selectedIndex;
            }

            UpdateCarousel();

            var maxSlots = _preferencesManager.Settings?.MaxCharacterSlots ?? 0;
            var fullSlots = _carouselProfiles.Count;
            NewCharacterButton.Disabled = fullSlots >= maxSlots;
            // CCM rework lobby - end
        }

        private void CreateCharacter()
        {
            // CCM rework lobby - start
            _preferencesManager.CreateCharacter(HumanoidCharacterProfile.Random());
            ReloadCharacterPickers();
            // CCM rework lobby - end
        }

        private void StepCarousel(int direction)
        {
            // CCM rework lobby - start
            if (_carouselProfiles.Count <= 1)
                return;

            _carouselIndex = (_carouselIndex + direction) % _carouselProfiles.Count;
            if (_carouselIndex < 0)
                _carouselIndex += _carouselProfiles.Count;

            var slot = _carouselProfiles[_carouselIndex].Slot;
            SelectCharacter?.Invoke(slot);
            // CCM rework lobby - end
        }

        private void PreviewClicked(GUIBoundKeyEventArgs args, int offset)
        {
            // CCM rework lobby - start
            if (args.Function != EngineKeyFunctions.UIClick)
                return;

            if (_carouselProfiles.Count <= 1)
                return;

            if (Math.Abs(offset) == 2 && _carouselProfiles.Count < 4)
                return;

            var targetIndex = (_carouselIndex + offset) % _carouselProfiles.Count;
            if (targetIndex < 0)
                targetIndex += _carouselProfiles.Count;

            _carouselIndex = targetIndex;
            SelectCharacter?.Invoke(_carouselProfiles[_carouselIndex].Slot);
            UpdateCarousel();
            args.Handle();
            // CCM rework lobby - end
        }

        private void UpdateCarousel()
        {
            // CCM rework lobby - start
            DeletePreviewEntities();
            _carouselLayoutMode = ResolveCarouselLayoutMode();
            ApplyCarouselLayoutMode(_carouselLayoutMode);

            if (_carouselProfiles.Count == 0)
            {
                SetPreview(LeftFarPreview, LeftFarNameLabel, null, default);
                SetPreview(LeftPreview, LeftNameLabel, null, default);
                SetPreview(CenterPreview, CenterNameLabel, null, default);
                SetPreview(RightPreview, RightNameLabel, null, default);
                SetPreview(RightFarPreview, RightFarNameLabel, null, default);
                LeftPreviewContainer.Visible = false;
                RightPreviewContainer.Visible = false;
                LeftFarPreviewContainer.Visible = false;
                RightFarPreviewContainer.Visible = false;
                return;
            }

            var center = _carouselProfiles[_carouselIndex];
            _centerPreviewEntity = CreatePreviewEntity(center.Profile, _showClothes);
            SetPreview(CenterPreview, CenterNameLabel, center.Profile, _centerPreviewEntity);
            if (center.Profile is HumanoidCharacterProfile humanoidCenter)
                _centerPreviewSpeciesId = humanoidCenter.Species;
            else
                _centerPreviewSpeciesId = SharedHumanoidAppearanceSystem.DefaultSpecies;

            if (_carouselProfiles.Count == 1 || _carouselLayoutMode == CarouselLayoutMode.One)
            {
                LeftPreviewContainer.Visible = false;
                RightPreviewContainer.Visible = false;
                LeftFarPreviewContainer.Visible = false;
                RightFarPreviewContainer.Visible = false;
                return;
            }

            LeftPreviewContainer.Visible = true;
            RightPreviewContainer.Visible = true;
            LeftFarPreviewContainer.Visible = _carouselLayoutMode == CarouselLayoutMode.Five && _carouselProfiles.Count >= 4;
            RightFarPreviewContainer.Visible = _carouselLayoutMode == CarouselLayoutMode.Five && _carouselProfiles.Count >= 4;

            var leftIndex = (_carouselIndex - 1 + _carouselProfiles.Count) % _carouselProfiles.Count;
            var rightIndex = (_carouselIndex + 1) % _carouselProfiles.Count;
            var leftFarIndex = (_carouselIndex - 2 + _carouselProfiles.Count) % _carouselProfiles.Count;
            var rightFarIndex = (_carouselIndex + 2) % _carouselProfiles.Count;

            var left = _carouselProfiles[leftIndex];
            var right = _carouselProfiles[rightIndex];
            var leftFar = _carouselProfiles[leftFarIndex];
            var rightFar = _carouselProfiles[rightFarIndex];

            _leftPreviewEntity = CreatePreviewEntity(left.Profile);
            _rightPreviewEntity = CreatePreviewEntity(right.Profile);
            if (_carouselLayoutMode == CarouselLayoutMode.Five && _carouselProfiles.Count >= 4)
            {
                _leftFarPreviewEntity = CreatePreviewEntity(leftFar.Profile);
                _rightFarPreviewEntity = CreatePreviewEntity(rightFar.Profile);
            }

            SetPreview(LeftPreview, LeftNameLabel, left.Profile, _leftPreviewEntity, true);
            SetPreview(RightPreview, RightNameLabel, right.Profile, _rightPreviewEntity, true);
            if (_carouselLayoutMode == CarouselLayoutMode.Five && _carouselProfiles.Count >= 4)
            {
                SetPreview(LeftFarPreview, LeftFarNameLabel, leftFar.Profile, _leftFarPreviewEntity, true);
                SetPreview(RightFarPreview, RightFarNameLabel, rightFar.Profile, _rightFarPreviewEntity, true);
            }
            else
            {
                SetPreview(LeftFarPreview, LeftFarNameLabel, null, default);
                SetPreview(RightFarPreview, RightFarNameLabel, null, default);
            }
            // CCM rework lobby - end
        }

        private void SetPreview(SpriteView view, Label label, ICharacterProfile? profile, EntityUid entity, bool dim = false)
        {
            // CCM rework lobby - start
            if (profile == null || entity == default)
            {
                view.SetEntity((EntityUid?) default);
                label.Text = string.Empty;
                return;
            }

            view.SetEntity((EntityUid?) entity);
            label.Text = profile.Name;
            view.Modulate = dim ? new Color(0.84f, 0.84f, 0.84f, 1f) : Color.White;
            label.Modulate = dim ? new Color(0.84f, 0.84f, 0.84f, 1f) : Color.White;
            // CCM rework lobby - end
        }

        private void RefreshCenterPreviewFromEditor(bool forceRespawn = false)
        {
            // CCM rework lobby - start
            var profile = _profileEditor.Profile;
            if (profile == null || _carouselProfiles.Count == 0)
                return;

            if (_profileEditor.CharacterSlot == null)
                return;

            if (_carouselProfiles[_carouselIndex].Slot != _profileEditor.CharacterSlot.Value)
                return;

            if (_centerPreviewEntity == default)
                return;

            var needsHumanoidRespawn = !_entManager.HasComponent<HumanoidAppearanceComponent>(_centerPreviewEntity);
            if (forceRespawn ||
                needsHumanoidRespawn ||
                profile.Species != _centerPreviewSpeciesId ||
                !_entManager.EntityExists(_centerPreviewEntity))
            {
                if (_centerPreviewEntity != default)
                    _entManager.DeleteEntity(_centerPreviewEntity);

                _centerPreviewEntity = CreatePreviewEntity(profile, _showClothes);
                _centerPreviewSpeciesId = profile.Species;
            }
            else
            {
                _entManager.System<HumanoidAppearanceSystem>().LoadProfile(_centerPreviewEntity, profile);
            }

            SetPreview(CenterPreview, CenterNameLabel, profile, _centerPreviewEntity);
            // CCM rework lobby - end
        }

        private EntityUid CreatePreviewEntity(ICharacterProfile profile, bool showClothes = true)
        {
            // CCM rework lobby - start
            if (profile is not HumanoidCharacterProfile humanoid)
            {
                var defaultSpecies = _protomanager.Index<SpeciesPrototype>(SharedHumanoidAppearanceSystem.DefaultSpecies);
                return _entManager.SpawnEntity(defaultSpecies.DollPrototype, MapCoordinates.Nullspace);
            }

            return UserInterfaceManager.GetUIController<LobbyUIController>()
                .LoadProfileEntity(humanoid, null, showClothes);
            // CCM rework lobby - end
        }

        private void UpdateShowClothes(bool showClothes)
        {
            // CCM rework lobby - start
            _showClothes = showClothes;
            RefreshCenterPreviewFromEditor(true);
            // CCM rework lobby - end
        }

        private void DeletePreviewEntities()
        {
            // CCM rework lobby - start
            if (_leftPreviewEntity != default)
                _entManager.DeleteEntity(_leftPreviewEntity);
            if (_centerPreviewEntity != default)
                _entManager.DeleteEntity(_centerPreviewEntity);
            if (_rightPreviewEntity != default)
                _entManager.DeleteEntity(_rightPreviewEntity);
            if (_leftFarPreviewEntity != default)
                _entManager.DeleteEntity(_leftFarPreviewEntity);
            if (_rightFarPreviewEntity != default)
                _entManager.DeleteEntity(_rightFarPreviewEntity);

            _leftPreviewEntity = default;
            _centerPreviewEntity = default;
            _rightPreviewEntity = default;
            _leftFarPreviewEntity = default;
            _rightFarPreviewEntity = default;
            // CCM rework lobby - end
        }

        private void UpdateRotation(float frameTime)
        {
            // CCM rework lobby - start
            if (_hoveredViews.Count == 0)
                return;

            foreach (var view in _hoveredViews)
            {
                _hoverRotationTimes[view] += frameTime;
                var progress = (_hoverRotationTimes[view] % 3f) / 3f;
                var direction = progress switch
                {
                    < 0.25f => Direction.South,
                    < 0.5f => Direction.West,
                    < 0.75f => Direction.North,
                    _ => Direction.East
                };

                view.OverrideDirection = direction;
            }
            // CCM rework lobby - end
        }

        private void HookPreviewRotation(PanelContainer container, SpriteView view, bool keepOrientationOnExit = false)
        {
            // CCM rework lobby - start
            container.OnMouseEntered += _ =>
            {
                _hoveredViews.Add(view);
                if (!keepOrientationOnExit || !_hoverRotationTimes.ContainsKey(view))
                {
                    _hoverRotationTimes[view] = 0f;
                    view.OverrideDirection = Direction.South;
                }
            };

            container.OnMouseExited += _ =>
            {
                _hoveredViews.Remove(view);
                if (!keepOrientationOnExit)
                {
                    _hoverRotationTimes[view] = 0f;
                    view.OverrideDirection = Direction.South;
                }
            };
            // CCM rework lobby - end
        }

        private void HandleDeletePressed()
        {
            // CCM rework lobby - start
            if (_carouselProfiles.Count == 0)
                return;

            if (_deleteReady)
            {
                DeleteCharacter?.Invoke(_carouselProfiles[_carouselIndex].Slot);
                ResetDeleteState();
                return;
            }

            _deleteCounting = true;
            _deleteCountdown = 3f;
            _deleteReady = false;
            DeleteCharacterButton.Modulate = new Color(1f, 0.7f, 0.7f, 1f);
            UpdateDeleteText();
            // CCM rework lobby - end
        }

        private void UpdateDeleteCountdown(float frameTime)
        {
            // CCM rework lobby - start
            if (!_deleteCounting)
                return;

            _deleteCountdown -= frameTime;
            if (_deleteCountdown <= 0f)
            {
                _deleteCounting = false;
                _deleteReady = true;
                DeleteCharacterButton.Modulate = new Color(1f, 0.3f, 0.3f, 1f);
                DeleteCharacterButton.Text = Loc.GetString("character-setup-gui-delete-confirm");
                return;
            }

            UpdateDeleteText();
            // CCM rework lobby - end
        }

        private void UpdateDeleteText()
        {
            // CCM rework lobby - start
            var seconds = Math.Max(1, (int) MathF.Ceiling(_deleteCountdown));
            DeleteCharacterButton.Text = Loc.GetString("character-setup-gui-delete-confirm-countdown", ("seconds", seconds));
            // CCM rework lobby - end
        }

        private void ResetDeleteState()
        {
            // CCM rework lobby - start
            _deleteCounting = false;
            _deleteReady = false;
            _deleteCountdown = 0f;
            DeleteCharacterButton.Modulate = Color.White;
            DeleteCharacterButton.Text = Loc.GetString("character-setup-gui-delete-character");
            // CCM rework lobby - end
        }

        private void StartDrag(GUIBoundKeyEventArgs args)
        {
            // CCM rework lobby - start
            if (args.Function != EngineKeyFunctions.UIClick)
                return;

            var headerHeight = WindowHeader.Size.Y > 0 ? WindowHeader.Size.Y : 24f;
            if (args.RelativePosition.Y > headerHeight)
                return;

            var global = args.PointerLocation.Position / UIScale;
            var closeMin = CloseButton.GlobalPosition;
            var closeMax = closeMin + CloseButton.Size;
            if (global.X >= closeMin.X && global.X <= closeMax.X &&
                global.Y >= closeMin.Y && global.Y <= closeMax.Y)
                return;

            _dragging = true;
            _dragOffset = args.PointerLocation.Position / UIScale - GlobalPosition;
            args.Handle();
            // CCM rework lobby - end
        }

        private void StopDrag(GUIBoundKeyEventArgs args)
        {
            // CCM rework lobby - start
            if (args.Function != EngineKeyFunctions.UIClick)
                return;

            _dragging = false;
            args.Handle();
            // CCM rework lobby - end
        }

        protected override void MouseMove(GUIMouseMoveEventArgs args)
        {
            base.MouseMove(args);
            DragMove(args);
        }

        private void DragMove(GUIMouseMoveEventArgs args)
        {
            // CCM rework lobby - start
            if (!_dragging)
                return;

            var topLeftGlobal = args.GlobalPosition - _dragOffset;
            var parentGlobal = Parent?.GlobalPosition ?? Vector2.Zero;
            var newPos = topLeftGlobal - parentGlobal;
            LayoutContainer.SetPosition(this, newPos);
            _manualPosition = newPos;
            _hasManualPosition = true;
            // CCM rework lobby - end
        }

        private void UpdateCarouselLayoutIfNeeded()
        {
            // CCM rework lobby - start
            var width = CarouselPanel.Size.X;
            if (width <= 0f)
                return;

            if (Math.Abs(width - _lastCarouselWidth) < 1f)
                return;

            _lastCarouselWidth = width;
            UpdateCarousel();
            // CCM rework lobby - end
        }

        private CarouselLayoutMode ResolveCarouselLayoutMode()
        {
            // CCM rework lobby - start
            if (_carouselProfiles.Count <= 1)
                return CarouselLayoutMode.One;

            var width = CarouselPanel.Size.X;
            if (width <= 0f)
                return _carouselProfiles.Count >= 4 ? CarouselLayoutMode.Five : CarouselLayoutMode.Three;

            const float minThreeWidth = 640f;
            const float minFiveWidth = 980f;

            if (width < minThreeWidth)
                return CarouselLayoutMode.One;

            if (_carouselProfiles.Count >= 4 && width >= minFiveWidth)
                return CarouselLayoutMode.Five;

            return CarouselLayoutMode.Three;
            // CCM rework lobby - end
        }

        private void ApplyCarouselLayoutMode(CarouselLayoutMode mode)
        {
            // CCM rework lobby - start
            switch (mode)
            {
                case CarouselLayoutMode.One:
                    CarouselPreviewRow.SeparationOverride = 8;
                    CenterPreviewContainer.MinSize = new Vector2(200f, 170f);
                    CenterPreview.Scale = new Vector2(6.4f, 6.4f);
                    LeftPreviewContainer.MinSize = new Vector2(140f, 130f);
                    RightPreviewContainer.MinSize = new Vector2(140f, 130f);
                    LeftFarPreviewContainer.MinSize = new Vector2(120f, 120f);
                    RightFarPreviewContainer.MinSize = new Vector2(120f, 120f);
                    LeftPreview.Scale = new Vector2(5.2f, 5.2f);
                    RightPreview.Scale = new Vector2(5.2f, 5.2f);
                    LeftFarPreview.Scale = new Vector2(4.6f, 4.6f);
                    RightFarPreview.Scale = new Vector2(4.6f, 4.6f);
                    break;
                case CarouselLayoutMode.Three:
                    CarouselPreviewRow.SeparationOverride = 10;
                    CenterPreviewContainer.MinSize = new Vector2(200f, 170f);
                    CenterPreview.Scale = new Vector2(6.6f, 6.6f);
                    LeftPreviewContainer.MinSize = new Vector2(150f, 140f);
                    RightPreviewContainer.MinSize = new Vector2(150f, 140f);
                    LeftFarPreviewContainer.MinSize = new Vector2(120f, 120f);
                    RightFarPreviewContainer.MinSize = new Vector2(120f, 120f);
                    LeftPreview.Scale = new Vector2(5.6f, 5.6f);
                    RightPreview.Scale = new Vector2(5.6f, 5.6f);
                    LeftFarPreview.Scale = new Vector2(4.8f, 4.8f);
                    RightFarPreview.Scale = new Vector2(4.8f, 4.8f);
                    break;
                default:
                    CarouselPreviewRow.SeparationOverride = 12;
                    CenterPreviewContainer.MinSize = new Vector2(220f, 180f);
                    CenterPreview.Scale = new Vector2(7f, 7f);
                    LeftPreviewContainer.MinSize = new Vector2(180f, 160f);
                    RightPreviewContainer.MinSize = new Vector2(180f, 160f);
                    LeftFarPreviewContainer.MinSize = new Vector2(160f, 140f);
                    RightFarPreviewContainer.MinSize = new Vector2(160f, 140f);
                    LeftPreview.Scale = new Vector2(6.4f, 6.4f);
                    RightPreview.Scale = new Vector2(6.4f, 6.4f);
                    LeftFarPreview.Scale = new Vector2(5.1f, 5.1f);
                    RightFarPreview.Scale = new Vector2(5.1f, 5.1f);
                    break;
            }
            // CCM rework lobby - end
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);

            if (!disposing)
                return;

            // CCM rework lobby - start
            DeletePreviewEntities();
            // CCM rework lobby - end
        }
    }
}
