using Content.Client._RMC14.Commendations;
using Content.Client._RMC14.RMCPlaytimeStats;
using Content.Client.Info;
using Content.Client.Info.PlaytimeStats;
using Content.Client.Resources;
using Content.Client.Interaction;
using Content.Shared.CCVar;
using Content.Shared.Preferences;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Input;
using System.Numerics;

namespace Content.Client.Lobby.UI
{
    /// <summary>
    /// Holds the entire character setup GUI, from character picks to individual character editing.
    /// </summary>
    [GenerateTypedNameReferences]
    public sealed partial class CharacterSetupGui : Control
    {
        [Dependency] private readonly IClientPreferencesManager _preferencesManager = default!;
        [Dependency] private readonly IEntityManager _entManager = default!;
        [Dependency] private readonly IPrototypeManager _protomanager = default!;
        [Dependency] private readonly IResourceCache _resourceCache = default!;
        [Dependency] private readonly IConfigurationManager _cfg = default!;

        private readonly Button _createNewCharacterButton;
        private readonly DragDropHelper<Control> _dragHelper;
        private bool _dragStarted;
        private Vector2 _dragOffset;
        private bool _dragAnchorInitialized;
        private Vector2 _lastGlobal;

        public event Action<int>? SelectCharacter;
        public event Action<int>? DeleteCharacter;

        public CharacterSetupGui(HumanoidProfileEditor profileEditor)
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);

            var panelTex = _resourceCache.GetTexture("/Textures/Interface/Nano/button.svg.96dpi.png");
            var back = new StyleBoxTexture
            {
                Texture = panelTex,
                Modulate = new Color(37, 37, 42)
            };
            back.SetPatchMargin(StyleBox.Margin.All, 10);

            BackgroundPanel.PanelOverride = back;
            MouseFilter = MouseFilterMode.Pass;
            OnKeyBindDown += OnDragKeyBindDown;
            OnKeyBindUp += OnDragKeyBindUp;

            _dragHelper = new DragDropHelper<Control>(OnBeginDrag, OnContinueDrag, OnEndDrag);

            _createNewCharacterButton = new Button
            {
                Text = Loc.GetString("character-setup-gui-create-new-character-button"),
            };

            _createNewCharacterButton.OnPressed += args =>
            {
                _preferencesManager.CreateCharacter(HumanoidCharacterProfile.Random());
                ReloadCharacterPickers();
                args.Event.Handle();
            };

            CharEditor.AddChild(profileEditor);
            CommendationsReceivedButton.OnPressed += _ =>
                IoCManager.Resolve<CommendationsManager>().OpenReceivedWindow();
            CommendationsGivenButton.OnPressed += _ =>
                IoCManager.Resolve<CommendationsManager>().OpenGivenWindow();

            _cfg.OnValueChanged(CCVars.SeeOwnNotes, p => AdminRemarksButton.Visible = p, true);
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);
            _dragHelper.Update(args.DeltaSeconds);

            if (Visible)
                _lastGlobal = GlobalPosition;
        }

        private void OnDragKeyBindDown(GUIBoundKeyEventArgs args)
        {
            if (args.Function != EngineKeyFunctions.UIClick || ShouldBlockDrag())
                return;

            _dragStarted = false;
            _dragHelper.MouseDown(this);
            args.Handle();
        }

        private void OnDragKeyBindUp(GUIBoundKeyEventArgs args)
        {
            if (args.Function != EngineKeyFunctions.UIClick)
                return;

            _dragHelper.EndDrag();
            args.Handle();
        }

        private bool OnBeginDrag()
        {
            if (Parent == null)
                return false;

            _dragStarted = true;

            var menuGlobal = _lastGlobal;
            if (!_dragAnchorInitialized)
                InitializeDragAnchor(menuGlobal);

            _dragOffset = UserInterfaceManager.MousePositionScaled.Position - menuGlobal;
            return true;
        }

        private bool OnContinueDrag(float frameTime)
        {
            if (!_dragStarted || Parent == null)
                return false;

            var parentGlobal = Parent.GlobalPosition;
            var mousePos = UserInterfaceManager.MousePositionScaled.Position;
            var newPos = mousePos - _dragOffset - parentGlobal;
            LayoutContainer.SetPosition(this, newPos);
            return true;
        }

        private void OnEndDrag()
        {
            _dragStarted = false;
        }

        private void InitializeDragAnchor(Vector2 menuGlobal)
        {
            if (_dragAnchorInitialized || Parent == null)
                return;

            var parentGlobal = Parent.GlobalPosition;
            LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.TopLeft);
            LayoutContainer.SetPosition(this, menuGlobal - parentGlobal);
            _dragAnchorInitialized = true;
        }

        private bool ShouldBlockDrag()
        {
            var hovered = UserInterfaceManager.CurrentlyHovered;
            if (hovered == null)
                return false;

            return hovered is BaseButton or LineEdit or Slider or ScrollBar or ScrollContainer;
        }

        /// <summary>
        /// Disposes and reloads all character picker buttons from the preferences data.
        /// </summary>
        public void ReloadCharacterPickers()
        {
            _createNewCharacterButton.Orphan();
            Characters.DisposeAllChildren();

            var numberOfFullSlots = 0;
            var characterButtonsGroup = new ButtonGroup();

            if (!_preferencesManager.ServerDataLoaded)
            {
                return;
            }

            _createNewCharacterButton.ToolTip =
                Loc.GetString("character-setup-gui-create-new-character-button-tooltip",
                    ("maxCharacters", _preferencesManager.Settings!.MaxCharacterSlots));

            var selectedSlot = _preferencesManager.Preferences?.SelectedCharacterIndex;

            foreach (var (slot, character) in _preferencesManager.Preferences!.Characters)
            {
                // Only show characters with allowed species
                var allowedSpecies = new[] { "Human", "Avali", "Arachnid", "Moth", "Felinid", "Dwarf" };
                if (character is HumanoidCharacterProfile humanoidProfile && !((IList<string>)allowedSpecies).Contains(humanoidProfile.Species.Id))
                    continue;

                numberOfFullSlots++;
                var characterPickerButton = new CharacterPickerButton(_entManager,
                    _protomanager,
                    characterButtonsGroup,
                    character,
                    slot == selectedSlot);

                Characters.AddChild(characterPickerButton);

                characterPickerButton.OnPressed += args =>
                {
                    SelectCharacter?.Invoke(slot);
                };

                characterPickerButton.OnDeletePressed += () =>
                {
                    DeleteCharacter?.Invoke(slot);
                };
            }

            _createNewCharacterButton.Disabled = numberOfFullSlots >= _preferencesManager.Settings.MaxCharacterSlots;
            Characters.AddChild(_createNewCharacterButton);
        }
    }
}
