using Content.Client._RMC14.Roadmap;
using Content.Client.CrewManifest;
using Content.Client.GameTicking.Managers;
using Content.Client._RMC14.Lobby;
using Content.Client.Info;
using Content.Client.Interaction;
using Content.Client.LateJoin;
using Content.Client.Stylesheets;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Content.Client.UserInterface.Systems.Guidebook;
using Content.Client.Voting.UI;
using Content.Client.Lobby;
using Content.Shared._RMC14.CCVar;
using Robust.Client.AutoGenerated;
using Robust.Client.Animations;
using Robust.Client.Console;
using Robust.Client.Graphics;
using Robust.Client.State;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Animations;
using Robust.Shared.Configuration;
using Robust.Shared.Network;
using Robust.Shared.Localization;
using Robust.Shared.Input;
using System;
using System.Numerics;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        [Dependency] private readonly IClientConsoleHost _consoleHost = default!;
        [Dependency] private readonly IConfigurationManager _cfg = default!;
        [Dependency] private readonly IEntityManager _entityManager = default!;
        [Dependency] private readonly IStateManager _stateManager = default!;

        private RulesAndInfoWindow? _tutorialWindow;
        private LateJoinGui? _lateJoinWindow;
        private VoteCallMenu? _voteMenu;
        private ObserveWarningWindow? _observeWindow;
        private bool _suppressReadyToggle;
        private bool _leftMenuVisible = true;
        private readonly DragDropHelper<Control> _leftMenuDragHelper;
        private bool _leftMenuDragStarted;
        private Vector2 _leftMenuDragOffset;
        private bool _leftMenuAnchorInitialized;
        private Vector2 _leftMenuLastGlobal;

        private const string LeftMenuHideAnimationKey = "lobby-left-menu-hide";
        private const string LeftMenuShowAnimationKey = "lobby-left-menu-show";

        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            _leftMenuDragHelper = new DragDropHelper<Control>(OnBeginLeftMenuDrag, OnContinueLeftMenuDrag, OnEndLeftMenuDrag);
            LayoutContainer.SetAnchorPreset(MainContainer, LayoutPreset.Wide);
            LayoutContainer.SetAnchorPreset(LeftColumn, LayoutPreset.Wide);
            LayoutContainer.SetAnchorPreset(DefaultState, LayoutPreset.Wide);
            LayoutContainer.SetAnchorPreset(CharacterSetupState, LayoutPreset.Wide);
            LayoutContainer.SetAnchorPreset(BackgroundViewportArea, LayoutPreset.Wide);
            LayoutContainer.SetAnchorPreset(Background, LayoutPreset.Wide);
            LayoutContainer.SetAnchorAndMarginPreset(CenterMenuGlow, LayoutPreset.Center);
            LayoutContainer.SetAnchorPreset(VoteContainer, LayoutPreset.TopLeft);
            LayoutContainer.SetAnchorAndMarginPreset(LobbyMusicPanel, LayoutPreset.TopRight, margin: 6);
            LayoutContainer.SetGrowHorizontal(LobbyMusicPanel, LayoutContainer.GrowDirection.Begin);

            SetupChatStyles();
            SetupLeftMenuToggle();

            LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
            OptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();
            GuidesButton.OnPressed += _ => UserInterfaceManager.GetUIController<GuidebookUIController>().ToggleGuidebook();
            UpdatesButton.OnPressed += _ => UserInterfaceManager.GetUIController<RoadmapUIController>().ToggleRoadmap();

            EmblemButton.OnPressed += _ => ToggleLeftMenu(false);
            LeftMenuToggleButton.OnPressed += _ => ToggleLeftMenu(true);

            TutorialButton.OnPressed += _ => OpenTutorial();
            SetupCharacterButton.OnPressed += _ => OpenCharacterSetup();
            PollsButton.OnPressed += _ => OpenPolls();
            ObserveButton.OnPressed += _ => OpenObserve();
            ReadyButton.OnToggled += args => ToggleReady(args.Pressed);
            JoinUsmcButton.OnPressed += _ => OpenLateJoin();
            JoinHiveButton.OnPressed += _ => UserInterfaceManager.GetUIController<RMCLobbyUIController>().OpenJoinXenoWindow();
            CrewManifestButton.OnPressed += _ => OpenCrewManifest();

            UpdateReadyLabel(ReadyButton.Pressed);
            ApplyLobbyTheme(_cfg.GetCVar(RMCCVars.RMCLobbyCrtEnabled));
            _cfg.OnValueChanged(RMCCVars.RMCLobbyCrtEnabled, ApplyLobbyTheme);
            _cfg.OnValueChanged(RMCCVars.RMCUIColorTheme,
                _ => ApplyLobbyTheme(_cfg.GetCVar(RMCCVars.RMCLobbyCrtEnabled)));
        }

        public void SwitchState(LobbyGuiState state)
        {
            DefaultState.Visible = false;
            CharacterSetupState.Visible = false;

            switch (state)
            {
                case LobbyGuiState.Default:
                    DefaultState.Visible = true;
                    RightSide.Visible = true;
                    break;
                case LobbyGuiState.CharacterSetup:
                    CharacterSetupState.Visible = true;

                    var actualWidth = (float) UserInterfaceManager.RootControl.PixelWidth;
                    var setupWidth = (float) LeftColumn.PixelWidth;

                    if (1 - (setupWidth / actualWidth) > 0.30)
                    {
                        RightSide.Visible = false;
                    }

                    UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();

                    break;
            }
        }


        public enum LobbyGuiState : byte
        {
            /// <summary>
            ///  The default state, i.e., what's seen on launch.
            /// </summary>
            Default,
            /// <summary>
            ///  The character setup state.
            /// </summary>
            CharacterSetup
        }

        public void SetReadyState(bool ready)
        {
            _suppressReadyToggle = true;
            ReadyButton.Pressed = ready;
            _suppressReadyToggle = false;
            UpdateReadyLabel(ready);
        }

        public void SetRoundState(bool roundStarted)
        {
            _suppressReadyToggle = true;
            ReadyButton.Disabled = roundStarted;
            if (roundStarted)
                ReadyButton.Pressed = false;
            _suppressReadyToggle = false;
            UpdateReadyLabel(ReadyButton.Pressed);

            ObserveButton.Disabled = !roundStarted;
            JoinUsmcButton.Disabled = !roundStarted;
            JoinHiveButton.Disabled = !roundStarted;
            CrewManifestButton.Disabled = !roundStarted;
        }

        private void SetupChatStyles()
        {
            Chat.ChatWindowPanel.AddStyleClass("LobbyChatPanelInner");
            Chat.ChatInput.AddStyleClass("LobbyChatInputPanel");
            Chat.ChatInput.Input.AddStyleClass("LobbyChatLineEdit");
            Chat.ChatInput.ChannelSelector.AddStyleClass("LobbyChatSelectorButton");
            Chat.ChatInput.FilterButton.AddStyleClass("LobbyChatFilterButton");
            Chat.ChatInput.MinSize = new Vector2(0f, 36f);
            Chat.ChatInput.Input.MinSize = new Vector2(0f, 28f);
        }

        private void SetupLeftMenuToggle()
        {
            EmblemButton.StyleBoxOverride = new StyleBoxEmpty();
            LeftMenuToggleButton.Visible = false;
            CenterMenuGlow.AnimationCompleted += OnLeftMenuAnimationCompleted;
            CenterMenuGlow.MouseFilter = Control.MouseFilterMode.Pass;
            CenterMenuPanel.MouseFilter = Control.MouseFilterMode.Pass;
            CenterMenuGlow.OnKeyBindDown += OnLeftMenuDragKeyBindDown;
            CenterMenuGlow.OnKeyBindUp += OnLeftMenuDragKeyBindUp;
        }

        private void ApplyLobbyTheme(bool crtEnabled)
        {
            SetThemeClass(CenterMenuGlow, crtEnabled);
            SetThemeClass(CenterMenuPanel, crtEnabled);
            SetThemeClass(ServerInfoPanel, crtEnabled);
            SetThemeClass(ServerInfoDivider, crtEnabled);
            SetThemeClass(ServerInfo, crtEnabled);
            SetThemeClass(RightSide, crtEnabled);
            SetThemeClass(Chat.ChatWindowPanel, crtEnabled);
            SetThemeClass(Chat.ChatInput, crtEnabled);
            SetThemeClass(Chat.ChatInput.Input, crtEnabled);
            SetThemeClass(Chat.ChatInput.ChannelSelector, crtEnabled);
            SetThemeClass(Chat.ChatInput.FilterButton, crtEnabled);
            SetThemeClass(CenterEmblem, crtEnabled);
            SetThemeClass(LeftMenuToggleButton, crtEnabled);
            SetThemeClass(WelcomeLine1, crtEnabled);
            SetThemeClass(WelcomeCharacterName, crtEnabled);
            SetThemeClass(WelcomeXenoName, crtEnabled);
            SetThemeClass(RoundStartTimer, crtEnabled);
            SetThemeClass(ReadyDivider, crtEnabled);
            SetThemeClass(ObserveDivider, crtEnabled);
            SetThemeClass(ServerInfoTitle, crtEnabled);
            SetThemeClass(StationTime, crtEnabled);
            SetThemeClass(LobbyMusicPanel, crtEnabled);
            SetThemeClass(LobbyMusicHeader, crtEnabled);
            SetThemeClass(LobbyMusicText, crtEnabled);

            SetThemeClass(UpdatesButton, crtEnabled);
            SetThemeClass(GuidesButton, crtEnabled);
            SetThemeClass(AHelpButton, crtEnabled);
            SetThemeClass(OptionsButton, crtEnabled);
            SetThemeClass(LeaveButton, crtEnabled);
            SetThemeClass(TutorialButton, crtEnabled);
            SetThemeClass(SetupCharacterButton, crtEnabled);
            SetThemeClass(PollsButton, crtEnabled);
            SetThemeClass(ObserveButton, crtEnabled);
            SetThemeClass(ReadyButton, crtEnabled);
            SetThemeClass(JoinUsmcButton, crtEnabled);
            SetThemeClass(JoinHiveButton, crtEnabled);
            SetThemeClass(CrewManifestButton, crtEnabled);

            ApplyGlow(WelcomeLine1, crtEnabled);
            ApplyGlow(WelcomeCharacterName, crtEnabled);
            ApplyGlow(WelcomeXenoName, crtEnabled);
            ApplyGlow(RoundStartTimer, crtEnabled);
            ApplyGlow(ServerInfoTitle, crtEnabled);
            ApplyGlow(LobbyMusicHeader, crtEnabled);

            ApplyButtonGlow(UpdatesButton, crtEnabled);
            ApplyButtonGlow(GuidesButton, crtEnabled);
            ApplyButtonGlow(AHelpButton, crtEnabled);
            ApplyButtonGlow(OptionsButton, crtEnabled);
            ApplyButtonGlow(LeaveButton, crtEnabled);
            ApplyButtonGlow(TutorialButton, crtEnabled);
            ApplyButtonGlow(SetupCharacterButton, crtEnabled);
            ApplyButtonGlow(PollsButton, crtEnabled);
            ApplyButtonGlow(ObserveButton, crtEnabled);
            ApplyButtonGlow(ReadyButton, crtEnabled);
            ApplyButtonGlow(JoinUsmcButton, crtEnabled);
            ApplyButtonGlow(JoinHiveButton, crtEnabled);

            Chat.SetLobbyTheme(true, crtEnabled);
        }

        private static void SetThemeClass(Control control, bool crtEnabled)
        {
            if (crtEnabled)
            {
                control.AddStyleClass(StyleNano.StyleClassLobbyThemeCrt);
                control.RemoveStyleClass(StyleNano.StyleClassLobbyThemeClean);
            }
            else
            {
                control.AddStyleClass(StyleNano.StyleClassLobbyThemeClean);
                control.RemoveStyleClass(StyleNano.StyleClassLobbyThemeCrt);
            }
        }

        private static void ApplyGlow(Label label, bool crtEnabled)
        {
            if (crtEnabled)
            {
                label.FontColorShadowOverride = StyleNano.LobbyCrtGlow;
                label.ShadowOffsetXOverride = 1;
                label.ShadowOffsetYOverride = 1;
            }
            else
            {
                label.FontColorShadowOverride = null;
                label.ShadowOffsetXOverride = null;
                label.ShadowOffsetYOverride = null;
            }
        }

        private static void ApplyButtonGlow(Button button, bool crtEnabled)
        {
            ApplyGlow(button.Label, crtEnabled);
        }

        private void ToggleLeftMenu(bool show)
        {
            if (_leftMenuVisible == show)
                return;

            _leftMenuVisible = show;
            CenterMenuGlow.StopAnimation(LeftMenuHideAnimationKey);
            CenterMenuGlow.StopAnimation(LeftMenuShowAnimationKey);

            if (show)
            {
                LeftMenuToggleButton.Visible = false;
                CenterMenuGlow.Visible = true;
                CenterMenuGlow.Modulate = Color.Transparent;
                CenterMenuGlow.PlayAnimation(BuildLeftMenuAnimation(Color.Transparent, Color.White), LeftMenuShowAnimationKey);
            }
            else
            {
                CenterMenuGlow.PlayAnimation(BuildLeftMenuAnimation(Color.White, Color.Transparent), LeftMenuHideAnimationKey);
            }
        }

        private void OnLeftMenuAnimationCompleted(string key)
        {
            if (key == LeftMenuHideAnimationKey)
            {
                CenterMenuGlow.Visible = false;
                CenterMenuGlow.Modulate = Color.White;
                LeftMenuToggleButton.Visible = true;
            }
        }

        private static Animation BuildLeftMenuAnimation(Color from, Color to)
        {
            return new Animation
            {
                Length = TimeSpan.FromSeconds(0.15f),
                AnimationTracks =
                {
                    new AnimationTrackControlProperty
                    {
                        Property = nameof(Control.Modulate),
                        InterpolationMode = AnimationInterpolationMode.Linear,
                        KeyFrames =
                        {
                            new AnimationTrackProperty.KeyFrame(from, 0f),
                            new AnimationTrackProperty.KeyFrame(to, 0.15f)
                        }
                    }
                }
            };
        }

        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);
            _leftMenuDragHelper.Update(args.DeltaSeconds);

            if (CenterMenuGlow.Visible)
                _leftMenuLastGlobal = CenterMenuGlow.GlobalPosition;
        }

        private void OnLeftMenuDragKeyBindDown(GUIBoundKeyEventArgs args)
        {
            if (args.Function != EngineKeyFunctions.UIClick || !CenterMenuGlow.Visible)
                return;

            _leftMenuDragStarted = false;
            _leftMenuDragHelper.MouseDown(CenterMenuGlow);
            args.Handle();
        }

        private void OnLeftMenuDragKeyBindUp(GUIBoundKeyEventArgs args)
        {
            if (args.Function != EngineKeyFunctions.UIClick)
                return;

            _leftMenuDragHelper.EndDrag();
            args.Handle();
        }

        private bool OnBeginLeftMenuDrag()
        {
            if (!CenterMenuGlow.Visible || CenterMenuGlow.Parent == null)
                return false;

            _leftMenuDragStarted = true;

            var menuGlobal = _leftMenuLastGlobal;
            if (!_leftMenuAnchorInitialized)
                InitializeLeftMenuAnchor(menuGlobal);

            _leftMenuDragOffset = UserInterfaceManager.MousePositionScaled.Position - menuGlobal;
            return true;
        }

        private bool OnContinueLeftMenuDrag(float frameTime)
        {
            if (!_leftMenuDragStarted || CenterMenuGlow.Parent == null)
                return false;

            var parentGlobal = CenterMenuGlow.Parent.GlobalPosition;
            var mousePos = UserInterfaceManager.MousePositionScaled.Position;
            var newPos = mousePos - _leftMenuDragOffset - parentGlobal;
            LayoutContainer.SetPosition(CenterMenuGlow, newPos);
            return true;
        }

        private void OnEndLeftMenuDrag()
        {
            _leftMenuDragStarted = false;
        }

        private void InitializeLeftMenuAnchor(Vector2 menuGlobal)
        {
            if (_leftMenuAnchorInitialized || CenterMenuGlow.Parent == null)
                return;

            var parentGlobal = CenterMenuGlow.Parent.GlobalPosition;
            LayoutContainer.SetAnchorPreset(CenterMenuGlow, LayoutPreset.TopLeft);
            LayoutContainer.SetPosition(CenterMenuGlow, menuGlobal - parentGlobal);
            _leftMenuAnchorInitialized = true;
        }


        private void UpdateReadyLabel(bool ready)
        {
            ReadyButton.Text = ready
                ? Loc.GetString("ui-lobby-ready-up-button")
                : Loc.GetString("ui-lobby-not-ready-button");
        }

        private void OpenTutorial()
        {
            if (_tutorialWindow == null || _tutorialWindow.Disposed)
            {
                _tutorialWindow = new RulesAndInfoWindow();
                _tutorialWindow.OnClose += () => _tutorialWindow = null;
            }

            _tutorialWindow.OpenCentered();
        }

        private void OpenCharacterSetup()
        {
            if (_stateManager.CurrentState is LobbyState lobby)
                lobby.SwitchState(LobbyGuiState.CharacterSetup);
        }

        private void OpenPolls()
        {
            if (_voteMenu == null || _voteMenu.Disposed)
            {
                _voteMenu = new VoteCallMenu();
                _voteMenu.OnClose += () => _voteMenu = null;
            }

            _voteMenu.OpenCentered();
        }

        private void OpenObserve()
        {
            if (_observeWindow == null || _observeWindow.Disposed)
            {
                _observeWindow = new ObserveWarningWindow();
                _observeWindow.OnClose += () => _observeWindow = null;
            }

            _observeWindow.OpenCentered();
        }

        private void OpenLateJoin()
        {
            if (_lateJoinWindow == null || _lateJoinWindow.Disposed)
            {
                _lateJoinWindow = new LateJoinGui();
                _lateJoinWindow.OnClose += () => _lateJoinWindow = null;
            }

            _lateJoinWindow.OpenCentered();
        }

        private void OpenCrewManifest()
        {
            if (!TryGetLobbyStation(out var station))
                return;

            _entityManager.System<CrewManifestSystem>().RequestCrewManifest(station);
        }

        private bool TryGetLobbyStation(out NetEntity station)
        {
            var gameTicker = _entityManager.System<ClientGameTicker>();

            foreach (var entry in gameTicker.StationNames)
            {
                station = entry.Key;
                return true;
            }

            foreach (var entry in gameTicker.JobsAvailable)
            {
                station = entry.Key;
                return true;
            }

            station = default;
            return false;
        }

        private void ToggleReady(bool ready)
        {
            if (_suppressReadyToggle)
                return;

            UpdateReadyLabel(ready);
            _consoleHost.ExecuteCommand($"toggleready {ready.ToString().ToLowerInvariant()}");
        }
    }
}
