using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Stories.Vehicle.UI.Status;

[GenerateTypedNameReferences]
public sealed partial class VehicleStatusWindow : DefaultWindow
{
    public VehicleStatusWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
