using Content.Client.Stylesheets;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Input;
using Robust.Shared.Maths;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client._RMC14.Xenonids.UI;

[GenerateTypedNameReferences]
[Virtual]
public partial class XenoChoiceControl : Control
{
    private StyleNano.UiColorTheme _appliedTheme;
    private bool _hovered;
    private bool _pressed;
    private string? _plainName;
    private FormattedMessage? _formattedName;

    public XenoChoiceControl()
    {
        RobustXamlLoader.Load(this);

        Button.OnMouseEntered += _ =>
        {
            _hovered = true;
            ApplyThemeColors(force: true);
        };
        Button.OnMouseExited += _ =>
        {
            _hovered = false;
            _pressed = false;
            ApplyThemeColors(force: true);
        };
        Button.OnKeyBindDown += args =>
        {
            if (args.Function != EngineKeyFunctions.UIClick)
                return;

            _pressed = true;
            ApplyThemeColors(force: true);
        };
        Button.OnKeyBindUp += args =>
        {
            if (args.Function != EngineKeyFunctions.UIClick)
                return;

            _pressed = false;
            ApplyThemeColors(force: true);
        };

        ApplyThemeColors(force: true);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);
        ApplyThemeColors();
    }

    public void Set(string name, Texture? texture)
    {
        _plainName = name;
        _formattedName = null;
        RefreshLabel();
        Texture.Texture = texture;
    }

    public void Set(FormattedMessage msg, Texture? texture)
    {
        _plainName = null;
        _formattedName = new FormattedMessage(msg);
        RefreshLabel();
        Texture.Texture = texture;
    }

    private void ApplyThemeColors(bool force = false)
    {
        var theme = StyleNano.CurrentTheme;
        if (!force && theme == _appliedTheme)
            return;

        _appliedTheme = theme;
        UpdateButtonStyle();
        RefreshLabel();
    }

    private void UpdateButtonStyle()
    {
        var blue = _appliedTheme == StyleNano.UiColorTheme.Blue;
        var normal = blue ? Color.FromHex("#133B74") : Color.FromHex("#0A4D11");
        var hover = blue ? Color.FromHex("#18488F") : Color.FromHex("#0D6316");
        var pressed = blue ? Color.FromHex("#0C2850") : Color.FromHex("#063B0B");
        var border = blue ? Color.FromHex("#3E78D7") : Color.FromHex("#35BA51");

        Button.StyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = _pressed ? pressed : _hovered ? hover : normal,
            BorderColor = border.WithAlpha(_hovered || _pressed ? 0.95f : 0.75f),
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 4,
            ContentMarginTopOverride = 2,
            ContentMarginRightOverride = 4,
            ContentMarginBottomOverride = 2,
        };
    }

    private void RefreshLabel()
    {
        var textColor = _appliedTheme == StyleNano.UiColorTheme.Blue
            ? Color.FromHex("#F0F6FF")
            : Color.FromHex("#F2FFF4");

        if (_formattedName != null)
            NameLabel.SetMessage(_formattedName, defaultColor: textColor);
        else
            NameLabel.SetMessage(_plainName ?? string.Empty, defaultColor: textColor);

        Texture.ModulateSelfOverride = textColor;
    }
}
