- type: entity
  abstract: true
  parent: RMCBaseMeleeWeapon
  id: CCMBaseMechGun
  components:
  - type: GunIFF
    enabled: false
  - type: RMCWeaponDamageFalloff
  - type: AltFireMelee
  - type: MeleeWeapon
    attackRate: 1
    damage:
      types:
        Blunt: 5
    soundHit:
      collection: GenericHit
  - type: EmitSoundOnPickup
    sound:
      collection: RMCEquipGun
  - type: EmitSoundOnLand
    sound:
      collection: RMCRustleGun
  - type: Gun
    meleeCooldownOnShoot: false
    resetOnHandSelected: false
    burstCooldown: 0
  - type: RMCWeaponAccuracy
  - type: Appearance
  - type: InteractionActivateOnClick
  - type: MultiHandedItem
  - type: ClothingSpeedModifier
    walkModifier: 0.5
    sprintModifier: 0.5
  - type: HeldSpeedModifier

- type: entity
  abstract: true
  parent: [ CCMBaseMechGun, BaseItem ]
  id: RMCBaseMechWeaponRifle
  components:
  - type: Gun
    selectedMode: FullAuto
    availableModes:
    - FullAuto
  - type: RMCSelectiveFire
    baseFireModes:
    - FullAuto
    recoilWielded: 1
    recoilUnwielded: 1
    scatterWielded: 5
    scatterUnwielded: 5
    modifiers:
      FullAuto:
        maxScatterModifier: 2
        useBurstScatterMult: true
        unwieldedScatterMultiplier: 1
        shotsToMaxScatter: 4
    baseFireRate: 4.5
    size: Ginormous
  - type: AmmoCounter
  - type: ContainerContainer
    containers:
      gun_magazine: !type:ContainerSlot
      gun_chamber: !type:ContainerSlot
  - type: Appearance