- type: department
  parent: CMDepartmentBase
  id: CMMilitaryPolice
  name: department-CMMilitaryPolice
  description: cm-department-MilitaryPolice-description
  color: "#DE3A3A"
  roles:
  - CMProvostInspector
  - CMChiefMP
  - CMMilitaryWarden
  - CMMilitaryPolice
  - CMProvostAdvisor #CCM14
  departmentRadio: MarineMilitaryPolice
  headOfDepartment: CMChiefMP
