- type: department
  parent: CMDepartmentBase
  id: CMAuxiliarySupport
  name: department-CMAuxiliarySupport
  description: cm-department-AuxiliarySupport-description
  color: "#C38312"
  roles:
  - CMAuxiliarySupportOfficer
  - CMPilotDropship
  - CMPilotGunship
  - CMDropshipCrewChief
  # - CMIntelOfficer CCM14
  # - CMVehicleCrewman CCM14
  # - CMSeniorEnlistedAdvisor CCM14
  departmentRadio: MarineJTAC
  headOfDepartment: CMAuxiliarySupportOfficer
