using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface.Fragments;
using Content.Shared._CCM.Mech.Components;
using Content.Shared._CCM.Mech;
using Content.Shared.Atmos;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using System.Linq;
using Robust.Client.UserInterface;
using Content.Shared._CCM.Mech.EntitySystems;
using Robust.Shared.IoC;
using Robust.Shared.GameObjects;
using System.Collections.Generic;

namespace Content.Client._CCM.Mech.Ui;

/// <summary>
/// Interface control for mechs.
/// </summary>
/// <seealso cref="MechBoundUserInterface"/>
[GenerateTypedNameReferences]
public sealed partial class CCMMechMenu : FancyWindow
{
    // Dependencies
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly ILocalizationManager _loc = default!;

    // State
    private EntityUid _mech;
    private bool _pilotPresent = false;
    private BoundUserInterface? _parentBui;

    // Events for the BUI to subscribe to
    public event Action<EntityUid>? OnRemoveButtonPressed;
    public event Action<EntityUid>? OnRemoveModuleButtonPressed;

    public CCMMechMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void SetEntity(EntityUid entity)
    {
        _mech = entity;

        this.SetInfoFromEntity(_entityManager, _mech);

        MechView.SetEntity(entity);
        MechName.Text = _entityManager.GetComponent<MetaDataComponent>(_mech).EntityName;
    }

    public void SetParentBui(BoundUserInterface parentBui)
    {
        _parentBui = parentBui;
    }

    public void UpdateMechStats()
    {
        if (_lastState != null)
        {
            if (_lastState.MaxIntegrity > 0f)
            {
                var integrityPercent = _lastState.Integrity / _lastState.MaxIntegrity;
                IntegrityDisplayBar.Value = integrityPercent;

                var integrityText = _lastState.IsBroken
                    ? _loc.GetString("mech-integrity-display-broken", ("amount", (int)(integrityPercent * 100)))
                    : _loc.GetString("mech-integrity-display", ("amount", (int)(integrityPercent * 100)));

                IntegrityDisplay.Text = integrityText;
            }
            else
            {
                IntegrityDisplayBar.Value = 0f;
                IntegrityDisplay.Text = _loc.GetString("mech-integrity-display", ("amount", 0));
            }

            if (_lastState.MaxEnergy > 0f)
            {
                var energyPercent = _lastState.Energy / _lastState.MaxEnergy;
                EnergyDisplayBar.Value = energyPercent;
                EnergyDisplay.Text = _loc.GetString("mech-energy-display", ("amount", (int)(energyPercent * 100)));
            }
            else
            {
                EnergyDisplayBar.Value = 0f;
                EnergyDisplay.Text = _loc.GetString("mech-energy-missing");
            }

            SlotDisplay.Text = _loc.GetString("mech-equipment-slot-display",
                ("used", _lastState.EquipmentUsed), ("max", _lastState.MaxEquipmentAmount));

            ModuleSlotDisplay.Text = _loc.GetString("mech-module-slot-display",
                ("used", _lastState.ModuleSpaceUsed), ("max", _lastState.ModuleSpaceMax));
        }
    }

    public void UpdateMechState(MechBoundUiState state)
    {
        _lastState = state;
        _pilotPresent = state.PilotPresent; 

        // Compare UI children vs new state to decide whether to rebuild
        var currentEquip = GetEquipmentNetEntities(EquipmentControlContainer);
        if (!currentEquip.SequenceEqual(state.Equipment))
            UpdateEquipmentView(state.Equipment);

        var currentMods = GetEquipmentNetEntities(ModuleControlContainer);
        if (!currentMods.SequenceEqual(state.Modules))
            UpdateModuleView(state.Modules);

        // Disable removing only if pilot is present
        SetRemoveDisabledForContainer(EquipmentControlContainer, _pilotPresent);
        SetRemoveDisabledForContainer(ModuleControlContainer, _pilotPresent);

        RefreshEquipmentFragmentStates(state);
    }

    private List<NetEntity> GetEquipmentNetEntities(Control container)
    {
        var result = new List<NetEntity>();
        foreach (var child in container.Children)
        {
            if (child is EquipmentControl control && control.Entity.IsValid())
            {
                result.Add(_entityManager.GetNetEntity(control.Entity));
            }
        }
        return result;
    }

    private void SetRemoveDisabledForContainer(Control container, bool disabled)
    {
        foreach (var child in container.Children)
        {
            if (child is EquipmentControl control)
            {
                control.SetRemoveDisabled(disabled);
            }
        }
    }

    private MechBoundUiState? _lastState;

    private void RefreshEquipmentFragmentStates(MechBoundUiState state)
    {
        UpdateFragmentsForContainer(EquipmentControlContainer, state.EquipmentUiStates);
        UpdateFragmentsForContainer(ModuleControlContainer, state.EquipmentUiStates);
    }

    private void UpdateFragmentsForContainer(Control container, Dictionary<NetEntity, BoundUserInterfaceState> states)
    {
        foreach (var child in container.Children)
        {
            if (child is EquipmentControl control)
            {
                var ent = control.Entity;
                var netEnt = _entityManager.GetNetEntity(ent);
                if (!states.TryGetValue(netEnt, out var eqState))
                    continue;

                var uicomp = _entityManager.GetComponentOrNull<UIFragmentComponent>(ent);
                if (uicomp?.Ui != null)
                {
                    uicomp.Ui.UpdateState(eqState);
                }
            }
        }
    }

    public void UpdateEquipmentView(List<NetEntity>? equipment = null)
    {
        if (equipment == null)
        {
            if (!_entityManager.TryGetComponent<CCMMechComponent>(_mech, out var mechComp))
                return;
            equipment = new List<NetEntity>();
            foreach (var ent in mechComp.EquipmentContainer.ContainedEntities)
                equipment.Add(_entityManager.GetNetEntity(ent));
        }

        EquipmentControlContainer.Children.Clear();
        foreach (var netEnt in equipment)
        {
            var ent = _entityManager.GetEntity(netEnt);
            if (!_entityManager.TryGetComponent<MetaDataComponent>(ent, out var metaData))
                continue;

            var uicomp = _entityManager.GetComponentOrNull<UIFragmentComponent>(ent);
            Control? ui = null;

            if (uicomp?.Ui != null)
            {
                uicomp.Ui.Setup(_parentBui!, ent);
                if (_lastState?.EquipmentUiStates.TryGetValue(netEnt, out var eqState) == true)
                {
                    uicomp.Ui.UpdateState(eqState);
                }

                ui = uicomp.Ui.GetUIFragmentRoot();
            }

            // Get equipment size
            var size = _entityManager.GetComponentOrNull<CCMMechEquipmentComponent>(ent)?.Size ?? 1;

            var control = new EquipmentControl(ent, metaData.EntityName, ui, size);
            control.OnRemoveButtonPressed += () => OnRemoveButtonPressed?.Invoke(ent);
            EquipmentControlContainer.AddChild(control);
        }
    }

    public void UpdateModuleView(List<NetEntity>? modules = null)
    {
        if (modules == null)
        {
            if (!_entityManager.TryGetComponent<CCMMechComponent>(_mech, out var mechComp))
                return;
            modules = new List<NetEntity>();
            foreach (var ent in mechComp.ModuleContainer.ContainedEntities)
                modules.Add(_entityManager.GetNetEntity(ent));
        }

        ModuleControlContainer.Children.Clear();
        foreach (var netEnt in modules)
        {
            var ent = _entityManager.GetEntity(netEnt);
            if (!_entityManager.TryGetComponent<MetaDataComponent>(ent, out var metaData))
                continue;

            Control? ui = null;
            var uicomp = _entityManager.GetComponentOrNull<UIFragmentComponent>(ent);
            if (uicomp?.Ui != null)
            {
                uicomp.Ui.Setup(_parentBui!, ent);
                if (_lastState?.EquipmentUiStates.TryGetValue(netEnt, out var modState) == true)
                {
                    uicomp.Ui.UpdateState(modState);
                }
                ui = uicomp.Ui.GetUIFragmentRoot();
            }

            // Get module size
            var size = _entityManager.GetComponentOrNull<CCMMechModuleComponent>(ent)?.Size ?? 1;

            var control = new EquipmentControl(ent, metaData.EntityName, ui, size);
            control.OnRemoveButtonPressed += () => OnRemoveModuleButtonPressed?.Invoke(ent);
            ModuleControlContainer.AddChild(control);
        }
    }

    /// <summary>
    /// Updates the UI state and refreshes all displays.
    /// </summary>
    public void UpdateState(MechBoundUiState state)
    {
        _lastState = state;
        UpdateMechState(state);
        UpdateMechStats();
    }
}

public sealed class EquipmentControl : Control
{
    public EntityUid Entity { get; }
    public event Action? OnRemoveButtonPressed;

    private readonly Button _removeButton;

    public EquipmentControl(EntityUid entity, string name, Control? customUi, int size)
    {
        Entity = entity;

        var mainContainer = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            HorizontalExpand = true
        };

        // Header with name and remove button
        var header = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true
        };

        header.AddChild(new Label { Text = name, HorizontalExpand = true });
        
        _removeButton = new Button { Text = "Remove" };
        _removeButton.OnPressed += _ => OnRemoveButtonPressed?.Invoke();
        header.AddChild(_removeButton);

        mainContainer.AddChild(header);

        // Size indicator
        mainContainer.AddChild(new Label { Text = $"Size: {size}" });

        // Custom UI if provided
        if (customUi != null)
        {
            mainContainer.AddChild(customUi);
        }

        AddChild(mainContainer);
    }

    public void SetRemoveDisabled(bool disabled)
    {
        _removeButton.Disabled = disabled;
    }
}
