- type: rank
  id: RMCRankTSEMarine
  name: Новиций
  prefix: Нов.
  paygrade: E1

- type: rank
  id: RMCRankTSELanceCorporal
  name: Велит
  prefix: Вел.
  paygrade: E2

- type: rank
  id: RMCRankTSECorporal
  name: Гастат
  prefix: Гас.
  paygrade: E3

- type: rank
  id: RMCRankTSESergeant
  name: Принцип
  prefix: Прин.
  paygrade: E4

- type: rank
  id: RMCRankTSEColourSergeant
  name: Триарий
  prefix: Триа.
  paygrade: E5

- type: rank
  id: RMCRankTSEWarrantOfficer1
  name: Претор
  prefix: Прет.
  paygrade: E6

- type: rank
  id: RMCRankTSEWarrantOfficer2
  name: Декан
  prefix: Дек.
  paygrade: E7

- type: rank
  id: RMCRankTSESecondLieutenant
  name: Турман
  prefix: Тур.
  paygrade: O1

- type: rank
  id: RMCRankTSELieutenant
  name: Декур
  prefix: Дек
  paygrade: O2

- type: rank
  id: RMCRankTSECaptain
  name: Центурион
  prefix: Цент.
  paygrade: O3

- type: rank
  id: RMCRankTSEMajor
  name: Манипул
  prefix: Ман.
  paygrade: O4

- type: rank
  id: RMCRankTSELieutenantColonel
  name: Турм-Тысячник
  prefix: Тур-Т.
  paygrade: O5

- type: rank
  id: RMCRankTSEColonel
  name: Тысячник
  prefix: Тыс.
  paygrade: O6

- type: rank
  id: RMCRankTSEBrigadier
  name: Векс
  prefix: Векс.
  paygrade: O7

- type: rank
  id: RMCRankTSEMajorGeneral
  name: Легат
  prefix: Лег.
  paygrade: O8

- type: rank
  id: RMCRankTSELieutenantGeneral
  name: Трибун
  prefix: Триб.
  paygrade: O9

- type: rank
  id: RMCRankTSEGeneral
  name: Принцепс
  prefix: Прин.
  paygrade: O10

# The below ranks are for the JAPANESE TSE marines. What does that mean? Why do they have two sets of ranks? Why does this exist? Why must we suffer like this?

- type: rank
  id: RMCRankEIAFNitoRikushi
  name: Nito Rikushi
  prefix: Nt-Shi.
  paygrade: E2

- type: rank
  id: RMCRankEIAFIttoRikushi
  name: Itto Rikushi
  prefix: It-Shi.
  paygrade: E3

- type: rank
  id: RMCRankEIAFRikushicho
  name: Rikushicho
  prefix: Shi.
  paygrade: E4

- type: rank
  id: RMCRankEIAFSantoRikuso
  name: Santo Rikuso
  prefix: St-Rik.
  paygrade: E5

- type: rank
  id: RMCRankEIAFNitoRikuso
  name: Nito Rikuso
  prefix: Nt-Rik.
  paygrade: E6

- type: rank
  id: RMCRankEIAFIttoRikuso
  name: Itto Rikuso
  prefix: It-Rik.
  paygrade: E7

- type: rank
  id: RMCRankEIAFRikusocho
  name: Rikusocho
  prefix: Rik.
  paygrade: E8

- type: rank
  id: RMCRankEIAFSantoKaii
  name: Santo Kaii
  prefix: St-Wei.
  paygrade: O1

- type: rank
  id: RMCRankEIAFNitoKaii
  name: Nito Kaii
  prefix: Nt-Wei.
  paygrade: O2

- type: rank
  id: RMCRankEIAFIttoKaii
  name: Itto Kaii
  prefix: It-Wei.
  paygrade: O3

- type: rank
  id: RMCRankEIAFSantoKaisa
  name: Santo Kaisa
  prefix: St-Sa.
  paygrade: O4

- type: rank
  id: RMCRankEIAFNitoKaisa
  name: Nito Kaisa
  prefix: Nt-Sa.
  paygrade: O5

- type: rank
  id: RMCRankEIAFIttoKaisa
  name: Itto Kaisa
  prefix: It-Sa.
  paygrade: O6

- type: rank
  id: RMCRankEIAFKaishoHo
  name: Kaisho-ho
  prefix: It-Sho.
  paygrade: O7

- type: rank
  id: RMCRankEIAFKaisho
  name: Kaisho
  prefix: Sho.
  paygrade: O8

- type: rank
  id: RMCRankEIAFBakuryochotarusho
  name: BakuryЕЌchЕЌ-taru-shЕЌ
  prefix: Bt-Sho.
  paygrade: O9

- type: rank
  id: RMCRankTSEEmpress
  name: Empress
  prefix: HRM.
# This needs to be changed to allow it to change dynamically for genders
