using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._RMC14.Commendations;

[GenerateTypedNameReferences]
public sealed partial class CommendationsWindow : DefaultCMWindow
{
    public CommendationsWindow()
    {
        RobustXamlLoader.Load(this);
    }
}

