- type: rank # CCM14
  id: RMCRankCMBDeputy
  name: БКМ помощник
  prefix: Пом.
  paygrade: БКМП

- type: rank
  id: RMCRankCMBMarshal
  name: БКМ Маршал
  prefix: Маршал
  paygrade: БКММ

- type: rank
  id: RMCRankCMBInvestigativeSynthetic
  name: БКМ следственный синтетик
  prefix: Синт.

- type: rank
  id: RMCRankCMBRiotControlSynthetic
  name: БКМ синтетик ОБсБ
  prefix: Синт.

- type: rank
  id: RMCRankCMBRiotControlOfficer
  name: БКМ борьба с беспорядками
  prefix: Оф.

- type: rank
  id: RMCRankCMBMedicalTechnician
  name: БКМ мед-техник
  prefix: Мед.

- type: rank
  id: RMCRankCMBBreachingTechnician
  name: БКМ техник прорыва
  prefix: Прор.

- type: rank
  id: RMCRankCMBSWATSpecialist
  name: БКМ специалист
  prefix: Спец.

- type: rank
  id: RMCRankICBAgent
  name: Агент бюро по контролю монополий
  prefix: Агент

- type: rank
  id: RMCRankICBCorporateLiaison
  name: Связной антимонопольного бюро
  prefix: АнтиМоп связ.
  paygrade: САМБ

- type: rank
  id: RMCRankIHROObserver
  name: Наблюдатель по ПРС
  prefix: "Набл."
  paygrade: НпПРС
