- type: rank # CCM14
  id: RMCRankWeYaOperator
  name: Ефрейтор
  prefix: Ефр.
  paygrade: ЧВК-ЕФ

- type: rank
  id: RMCRankWeYaEnforcer
  name: Силовик
  prefix: Сил.
  paygrade: ЧВК-СИЛ

- type: rank
  id: RMCRankWeYaVehicleSpecialist
  name: Специалист-механик
  prefix: Спц-мех.
  paygrade: ЧВК-СМ

- type: rank
  id: RMCRankWeYaSupportSpecialist
  name: Боевая Поддержка
  prefix: БП.
  paygrade: ЧВК-БП

- type: rank
  id: RMCRankWeYaMedicalSpecialist
  name: Медик
  prefix: Мед.
  paygrade: ЧВК-МЕД

- type: rank
  id: RMCRankWeYaWeaponSpecialist
  name: Спец по Вооружению
  prefix: СпВ.
  paygrade: ЧВК-СПЕЦ

- type: rank
  id: RMCRankWeYaXenoSpecialist
  name: Спец по Сдерживанию
  prefix: СпС.
  paygrade: ЧВУ-СПС

- type: rank
  id: RMCRankWeYaTraumaSurgeon
  name: Хирург-Травматолог
  prefix: Др.
  paygrade: ЧВК-ДОК

- type: rank
  id: RMCRankWeYaCorporateTechnician
  name: Техник
  prefix: Тех.
  paygrade: ЧВК-ТЕХ

- type: rank
  id: RMCRankWeYaEliteResponder
  name: Гвардеец
  prefix: ГВАР.
  paygrade: ЧВК-ГВР

- type: rank
  id: RMCRankWeYaEliteMedic
  name: Боевой Фельдшер
  prefix: БФ.
  paygrade: ЧВК-ФЛД

- type: rank
  id: RMCRankWeYaEliteGunner
  name: Ударник
  prefix: УДАР.
  paygrade: ЧВК-УДР

- type: rank
  id: RMCRankWeYaPMCSynthetic
  name: Синтетик
  prefix: Синт.
  paygrade: ЧВК-СИНТ

- type: rank
  id: RMCRankWeYaTeamLeader
  name: Старшина
  prefix: Стар.
  paygrade: ЧВК-СТ

- type: rank
  id: RMCRankWeYaFieldOperaionsLeader
  name: Урядник
  prefix: Уряд.
  paygrade: ЧВК-УР

- type: rank
  id: RMCRankWeYaForceLeader
  name: Поручник
  prefix: Пор.
  paygrade: ЧВК-ПОР

- type: rank
  id: RMCRankWeYaEliteTeamLeader
  name: Полевой Маршал
  prefix: ПМ.
  paygrade: ЧВК-МАР

- type: rank
  id: RMCRankWeYaSiteDirector
  name: Куратор Подразделения ЧВК
  prefix: Кур.
  paygrade: ЧВК-КУР

- type: rank
  id: RMCRankWeYaForceCommand
  name: Ротмеистер
  prefix: РМ.
  paygrade: ЧВК-РОТ

- type: rank
  id: RMCRankWeYaWhiteout
  name: Отряд "Белая мгла"
  prefix: ОБМ.
  paygrade: ???
