lore-examinable-verb-text = Лор
lore-examinable-verb-disabled = Узнать больше об объекте.
rmc-lore-examinable-trimax-polarized-shades = последняя технология TriMax - "TactOptix" одна из самых популярных продукций за этот год! Оснащены слабым бронированным стеклом, которые могут защитить от лёгких шрапнельных осколоков. Крайне популярна среди солдат на фронте а также разведчиков глубоко космоса, как военных так и независимых авантюристов, официальные источники утверждают "проверены в боях, одобрены солдатами ОПЗ!" Ходят слухи, что некоторым счастливчикам удалось выжить после выстрела лазерного оружия на близком расстоянии, хотя TriMax продолжает свою позицию "Перестаньте вставать под лазер и проверять это!"
rmc-lore-examinable-trimex-personal-shades = рекламируются как 'TriMex', (гениальная мысль использовать Е для обхода авторских прав), подделки популярны среди независимых "авантюристов" и у тех кто хочет казаться крутым. В то время как оригинал хвастается официальной защитой от атомной вспышки, радиации и лазеров, эти дешевые подделки едва хватает на защиту от УФ-лучей. Что с той знаменитой истории об отражении лазерного оружия от оригинала? Вряд ли кто-то поверит, что с такими очками это возможно. Но, они дешевы, и их слоган что то вроде "Экономь деньги и выгляди какой крутой космический рейнджер" на удивление это существенно повышает продажи.
rmc-lore-examinable-m3-eod-pattern-heavy-armor = эта версия брони была разработана во время войны между СССП и ОПЗ. Созданная для полевых техников, которые были назначенны саперами (EOD) во время конфликта, она предоставляет довольно эффективную бронирование для обычного морпеха. Наплечники и наколенники сделанные из пластин были значительно укреплены и модифицированы, прикрывая важные части каждой конечности. Для этой брони была разработана специальная противоосоколочная система, использовавшия ту же технологию, что и разрабатывавшийся в то же время бронежилет M70.

rmc-lore-examinable-armor-xm4-pattern-intel-armor = совершенство от AEGIS. На броне используется система, которая работает от нескольких подключенных датчиков движения на броне, , закрепленные на нагруднике. Если подключить ее к оптическому визору то будет имитировать работу датчика движения M314, повышая это значительно повышает эффективность в разведывательных операциях для отслеживания ситуации. Сейчас активно участвует в испытаниях на разведывательных миссиях или специально выделенных лабораторий.
rmc-lore-examinable-thirteen-loko = редкий продукт на рынке, Thirteen Loko — земной продукт. Такое название было придумано из-за стериотипа, что данный напиток будут пить только безумцы. Энергетик приобрёл известную не в лучшем свете репутацию, а после фанбазу. После многочисленных судебных исков и разбирательств на  Viteztvi, яд кобры был убран из рецепта, что сильно разочаровало потребителей напитка.

rmc-lore-examinable-boda = созданная ещё в 3000 году, реклама кампании BODA изначально была попыткой СССП завоевать сердца и умы колонизаторов по всему космосу. Вскоре после этого везде начали появляться бирюзовые торговые автоматы BODA, а большие запасы данного напитка стали появляться на складах ООН без прямых поставщиков. Несмотря на предостережения, после многочисленных экспериментов и исследований, которые выяснили, что продукция BODA безопасна для употребления, а также удивительно популярна, неизвестный излишек BODA был одобрен к использованию на колониях, ассоциируемые с ООН. Впоследствии он пользовался популярностью, прежде чем пропасть в безвестность в далекие десятилетия, когда запасы все больше и больше истощались.

rmc-lore-examinable-red-hot-bottle = предпологается что соус создавался как что то среднее между кетчупом и острым перцем, соус получил невероятную популярность и признание OOH, после этого он часто начал появляться не только на колониях, но ещё и на космических кораблях. Неожиданная популярность и признание любопытно совпало с закрытием первого оригинального соуса "ULTRA". Совпадение?

rmc-lore-examinable-pitchblende = Колонии по всех галактике добывают урановую руду, она используется для питания устаревших ядерных реакторов, позже началась военная программа, где урановую руду начали использовать в бронебойных боеприпасах, исследовательская группа нанятая VI подтвердило, что вред от излучаемой радиации "незначителен" и безопасен для человека. 

rmc-lore-examinable-bottle-of-bone-gel = Костный гель - биологический аналог кости с использованием крепкой специальной глины, костный гель может излечить как лёгкие переломы, так и тяжёлые. Костный гель не стоит использовать для лечения костного мозга, это может привести к... Не самому приятному результату. Черезмерное использование данного геля приводит к ухудшению иммунитета, прочности природных костей а также нехватке кальция.

rmc-lore-examinable-fountain-pen =
    "это больше, чем просто канцелярия, она получила признание и авторитет внутри ККМП ОПЗ, такая элитная ручка выдаётся исключительно старшему командному составу корпуса, является престижем и статусом, а в руках знаком хорошего командира.
    AEGIS известен своими разработками и исследованиями в области вооружения, но ручка это нечто оссобеное. Они сохранили все свои принципы для разработки этой ручки. Элегантность и эффективность главное составляющее, словно хорошее оружие - не требует многого, но эффективно во всех ситуациях.
   Золото используется на ручке для придания не только элегантности, но и прочности, проффесианальнальный сплав металла и золота, крепление и составляющее, это символизирует офицеров ККМП ОПЗ. Проффесианализм и прочность с предачей элегантности.
   Ручка имеет у себя многофункциональную систему смены цвета, на основе системы наведения вооружения - ручка использует специально разработанный механизм подачи разных чернил в стержень, при этом нарушение механизме не может повредить общей работе ручки.
Цвета чернил выбраны в соответствии с различными структурами и званиями ККМП ОПЗ, также есть особо яркие цвета для подчеркивания важного текста, что позволяет писать не только эффективно, но и в соответствии с своей структурой и должностью.
    Несмотря на роскошный и дорогой вид ручки, это не мешает также быть ей эффективной, ручка имеет крепкое металлическое покрытие, длинный стержень и долговечность конструкции, сплавы металлов корпуса не ржавеют и не повержены коррозии. Это учитывает все сложные ситуации - данный ручки эффективны для огромного объема работ для высших офицеров ОПЗ, а также полевых командиров.
    Роскош, элегантность и эффективность это слияние личностей упорных лидеров в лице офицеров ККМП ОПЗ, это настоящая награда и наследие, AEGIS утверждает - это не просто ручка. Это сердца и мужества армии ОПЗ, переданные в канцелярию. Это награда и реликвия. Хотя конкуренты  AEGIS утверждают, что огромные речи и рекламная кампания созданы для поднятия авторитета и стоимости ручек."

rmc-lore-examinable-s5-red-dot-sight = Многофункциональный погодный прицел S5 оснащен специальными линзами, которые способны приглушать слишком яркий свет для эффективности, а также устойчив к погодным условиям, настоящая гениальная мысль военных инженеров и снайперов, до того как узнаешь, что это гражданский вариант с наклеенной эмблемой армии ОПЗ. Использует обозначение AN/PVQ-64 Dot Sight


rmc-lore-examinable-s6-reflex-sight = рефлекторный прицел, простой в своей системе, громоздкий и сделан для долгой службы, используется для более сложных и ограниченных военных расчётах, совместим с многими рельсовыми системами и устанавливается почти на все вооружение. использует обозначение AN/PVG-72 Reflex Sight

-- Телескопический прицел S8 (4x)
rmc-lore-examinable-s8-4x-telescopic-scope = Телескопический прицел S8 одна из самых простых, долговечных и эффективных моделей прицелов, примерная максимальная дальность 780 м с использованием 10.24 мм патронов. Что в общем неплохо для данного прицела. Сделан  организацией Armat и носит обозначения AN/PVQ-31 4x Optic.

rmc-lore-examinable-s4-2x-telescopic-mini-scope = A light-duty optic, designated as the AN/PVQ-45 2x Optic. Suited towards short to medium-range engagements. Users are advised to zero it often, as the first mass-production batch had a tendency to drift in one direction or another with sustained use.
rmc-lore-examinable-b8-smart-scope = An experimental fire-control optic capable of linking into compatible IFF systems on certain weapons, designated the XAN/PVG-110 Smart Scope. Experimental technology developed by AEGIS, who have assured that all previously reported issues with false-negative IFF recognitions have been solved. Make sure to check the sight after every deployment, just in case.
rmc-lore-examinable-laser-sight = A standard visible-band laser module designated as the AN/PEQ-42 Laser Sight. Can be mounted onto any firearm that has a lower rail large enough to accommodate it.
rmc-lore-examinable-xm-vesg-1-flamer-nozzle = The Experimental Volatile-Exothermic-Sphere-Generator clip-on nozzle attachment for the M34 incinerator unit was specifically designed to allow marines to launch fireballs into enemy foxholes and bunkers. Despite the gel and resin coating, the flaming ball of naptha tears apart due the drag caused by launching it through the air, leading marines to use the attachment as a makeshift firework launcher during shore leave.
rmc-lore-examinable-hjra-12-extreme-intensity-incendiary-rocket = This incendiary rocket uses an experimental chemical designated 'R-189' by the SPP. It is designed to melt through fortifications and bunkers but is most commonly used in an anti-personnel role due to over-issuing and the tempeartures after use in its intended role leaving behind a cloud of super-heated air, preventing troops' advance.
rmc-lore-examinable-ar10-assault-rifle = The AR10 was initially manufactured by the Armalite corporation (bought by Weston-Yamada in 2002) in the 1950s. It was the first production rifle to incorporate many new and innovative features, such as a gas operated bolt and carrier system. Only 10,000 were ever produced, and the only national entities to use them were Portugal and Sudan. Since the end of the 20th century, these rifles - alongside the far more common M16 and AR15 - have floated around the less civillised areas of space, littering jungles and colony floors with their uncommon cased ammunition - a rarity since the introduction of pulse munitions. This rifle has the word \"Salazar\" engraved on its side.
rmc-lore-examinable-m54c-ap-magazine = Unlike standard HEAP magazines, these reserve bullets do not have depleted uranium tips. Instead, these rounds trade off some of their bullet package for a lighter weight, reducing damage but increasing penetration capabilities and muzzle velocity.
rmc-lore-examinable-xm-88-heavy-rifle = Originally developed by AEGIS Battlefield Armaments for the government of the state of Greater Brazil for use against mechanized infantry. The platform features an onboard computerized targeting system, sensor array, and an electronic autoloader; these features work in tandem to reduce and render inert armor on the users target with successive hits. The Almayer was issued a small amount of XM88s while preparing for Operation Swamp Hopper with the UNS Nan-Shan.
rmc-lore-examinable-type-64-submachine-gun = The Type 64 finds its way into the hands of more than just SPP soldiers, it has an active life with rebel groups, corporate security forces, mercenaries, less well-armed militaries, and just about everything or everyone in between.
rmc-lore-examinable-ssg45 = Chambered in 7x62mm caseless rounds, it offers superior stopping power and ammunition efficiency compared to the M54C MK2, while maintaining comparable performance in close-quarters engagements. Weston-Yamada’s PMC forces found the UNMC’s M54C increasingly ill-suited to their operational demands, particularly in extended-range missions where precision and firepower were paramount. This dissatisfaction prompted Weston-Yamada’s R&D division to design the SSG, tailoring it to meet the specific needs of their operatives.
rmc-lore-examinable-lady-fingers = A bold experiment in marketing, these brutal, unfiltered menthol cigarettes come in dusty rose packaging aimed at the women of the UNMC. The scent is so overpowering that they are sometimes used to keep bugs out of field tents. Despite the effort, they are rarely chosen and mostly sit untouched in vending machines, quietly daring someone to try. Whether anyone actually likes them is another question.
rmc-lore-examinable-kierland-electro-golds = Popularized by Novaris workers during the construction of its premier station, these cigarettes lit easily, burned evenly, and offered a straightforward, dependable smoke. The flat, dusty flavor and steady draw quickly made them a colonial staple. Kierlan later scaled production on frontier farming worlds and locked in exclusive trade deals with the UNMC.
rmc-lore-examinable-emerald-greens = Instantly recognizable by their price that undercuts even water, these cigarettes have become a fixture wherever budgets and morale run low. Nobody is quite sure what goes into the blend, but most agree you don't buy Emerald Greens for the flavor.
rmc-lore-examinable-boots-07 = A large portion of the magazine describes the B18 Defensive Armor, how it is designed to make the modern marine invincible and that it has recently finished trials, raising the expectations of the brass for this new piece of gear.
rmc-lore-examinable-boots-45 = The first part of the article explains basic sidearm maintenance and includes a small advertisement for a well-known gunsmith on Gateway Station. The second describes the best positions to sleep with your sidearm under the pillow in case of unexpected seditious activity.
rmc-lore-examinable-boots-58 = The article contained within describes the experience of the 1st FORECON Battalion veterans in the Tientsin campaign and the harsh jungle environment they had to go through when dealing with SPP and Local Guerrillas.
rmc-lore-examinable-boots-113 = The article details the fierce urban combat the marines had to face against human colonists on Mars during the early days of its colonization. As Weston Yamada was expanding on the red frontier, they faced armed resistance from colonists who refused the corporate expansion. Weston Yamada PMCs with the help of nearby UNMC forces fought off the insurrectionists. The article also mentions a few accounts from tankers on the effectiveness of their new main battle tanks, and recent sightings of MARSOC operators in the AO. This conflict marked one of the first recorded uses of orbital bombardments in active combat by the UNMC, with the UNS Omaha involved.
rmc-lore-examinable-boots-150 = A large portion of this issue explains SPP field rations aren't standardized and are produced at a local level. Because of this, captured and confiscated SPP rations have included some odd choices such as duck liver, century eggs, lutefisk, pickled pig snout, canned tripe, and dehydrated candied radish snacks.
rmc-lore-examinable-orrery-65 = Half of this issue is taken up by rumors of a Senior Executive misfiling his Quarterly Profit Report for Danton's Perch with the PMC Dispatch Division. After it is a debate article between two Executives from Special Services, regarding the creation of a colony in the Mu Arae system. The debate is centered around the location of the colony: one Executive thinks the colony should be a sub-orbital gas harvester around a gas giant, while the other thinks it should be located on the gas giant's verdant moon. Halfway through the debate, both Executives appear to lose their composure, and start slinging insults. The rest of the article appears to be heavily censored after that point.
rmc-lore-examinable-orrery-175 = The centrepiece of this issue is a story regarding the creation of a new vessel for the Navy, designed to be not only withstand all sorts of damage and attacks, but also contain enough firepower to destroy a city. The article explains that this is a joint project between the TSE and Weston-Yamada, and interviews the various WeYa and Imperial Engineers working on the ship. Although no confidential information is contained within, the repeated mention of railguns, triple point-defence lasers, and a suite of missile tubes gives you a good idea as to the strength of the vessel.
rmc-lore-examinable-orrery-184 = This special issue covers a few the various projects being undertaken by the Weston-Yamada Corporation which have been cleared for a press release by the Stakeholders and the Division Director. Notable projects include the UY-21 Weston-Yamada Blending Unit (Which fixes the UY-20's tendency to explode under heat), a 'prototype portable heavy mining laser' designed to cut through rock like butter, and a Weston-Yamada MANPADS system (Designated the TYPHOON EK-403) designed for PMC usage. Halfway through the issue, the magazine offers a 'Buy one, get one free' coupon for a pack of Sequoia beer; it appears to have expired the day after the issue was published.
