name: "Labels: Size"
on: pull_request_target
jobs:
  size-label:
    runs-on: ubuntu-latest
    steps:
      - name: size-label
        uses: "pascalgn/size-label-action@v0.5.5"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          # Custom size configuration
          sizes: >
            {
              "0": "размер: XS",
              "10": "размер: S",
              "100": "размер: M",
              "1000": "размер: L",
              "5000": "размер: XL"
            }
